### ISSUE TITLE
Implement our own protocol for remote logging

### ISSUE THREAD

**Issue by fflorent** [firebug/firebug.next#103]
Follow-up for issue #23.
I think it would be worthy to introduce our own protocol to log remote messages (except if a prior of art reveals that something similar exists).
The things that the protocol should implement:
- push the logs from the server to the browser (VS through HTTP response headers)
- being able to go through complex objects like when using grips

I think using WebSockets to do so. It offers the bidirectional communication between the client and the server, and also deals with timeouts easily (so we can destroy the server can destroy the objects being logged).
Maybe also using grips (or similar) to display the objects and their properties.

What do you think?

Florent

**Comment by janodvarko** [comment]
Server side logging is now platform feature, so related bugs should be reported in Bugzilla
https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox&component=Developer%20Tools%3A%20Console

Honza

**Comment by cadorn** [comment]
The link does not seem to work. Is there an example on how to use it somewhere? A link to an API?

**Comment by janodvarko** [comment]
The last link I posted opens Bugzilla "Enter Bug: Firefox" page for me.
It doesn't work for you?

Honza

**Comment by cadorn** [comment]
Ah ok. I thought it linked to s specific issue.
