### ISSUE TITLE
Broken side panel in NETWORK

### ISSUE THREAD

**Issue by aakash-cr7** [firebug/firebug.next#130]
![brokensidepaneln](https://cloud.githubusercontent.com/assets/7534680/4576373/83ca7d88-4fb2-11e4-9e49-59beb5c84372.png)

On my machine the side panel appears to be broken, Just want to check if it's me only or is it  a problem?
@fflorent  @simonlindholm @janodvarko 

Aakash

**Comment by aliuk2012** [comment]
Shouldn't this issue be closed if its fixed and in alpha 1?

**Comment by fflorent** [comment]
> Shouldn't this issue be closed if its fixed and in alpha 1?

Yep.

Florent
