### ISSUE TITLE
Properly style console.table() output

### ISSUE THREAD

**Issue by SebastianZ** [firebug/firebug.next#136]
The output of [`console.table()`](https://developer.mozilla.org/en-US/docs/Web/API/Console.table) calls should look more Firebug-ish.

Looks like:
![console.table output in DevTools](https://cloud.githubusercontent.com/assets/958943/4636173/751e30fe-53e0-11e4-8aba-dba799ad882b.png)

Should look more like:
![console.table output in Firebug](https://cloud.githubusercontent.com/assets/958943/4636177/7a5bf862-53e0-11e4-9050-bcf1959e5361.png)

**Tasks are:**
* Change the column header styles
* Hide the separators between the columns
* Change the cell styles

What should be kept:
* Table width should **not** expand to the whole width of the *Console* panel
* Line background colors should not be altered (as in other parts of Firebug like e.g. the *Net* panel)
* The index column
* Resizing the columns should still work

Sebastian

**Comment by aliuk2012** [comment]
This issue looks good to go, or is it still being reviewed?

**Comment by janodvarko** [comment]
This looks already great!

@krtkmj: I made a few minor changes:
1. New styles moved  into webconsole.css (we want to get rid of firebug-theme.css eventually)
2. All new styles prefixed by .theme-firebug .consoletable (so, they don't affect other things)

Committed a merged to the master.
Can you please verify?

https://github.com/firebug/firebug.next/commit/3e29e562a35f3e0ace74278fc1c2d994b453e41b

Thanks!
Honza

P.S: I noticed that you did some changes write no lol
can you please double check that they are properly merged in the master?

Honza

**Comment by janodvarko** [comment]
$fixed firebug-3.0.0-alpha.9

http://getfirebug.com/releases/firebug/3.0/firebug-3.0.0-alpha.9.xpi

Honza
