### ISSUE TITLE
Alignment bug in Command editor buttons

### ISSUE THREAD

**Issue by thomasandersen** [firebug/firebug.next#159]
The buttons should be aligned. 
See the screenshot where the Copy button is not properly aligned.

![screen shot 2014-10-23 at 17 44 59](https://cloud.githubusercontent.com/assets/194093/4756197/9c548226-5acb-11e4-9ecd-983d30b2cb4e.png)

**Comment by janodvarko** [comment]
Should be ok now.

Honza
