### ISSUE TITLE
Firebug.next theme is not compatible with DevEd Dark Theme

### ISSUE THREAD

**Issue by petruta** [firebug/firebug.next#177]
Reproducible using Firefox Developer Edition under all platforms.

STR: Install Firebug 3.0.0 on a clear profile or upgrade from Firebug 2.0.5 to 3.0.0

ER: The DevEd Dark theme remains active

AR: The standard theme replaces DevEd theme

**Comment by loonydevil** [comment]
guys, I'm still facing the issue, moreover, after I uninstalled firebug the setting for devedition themes still locked in settings. what am I doing wrong?
