### ISSUE TITLE
firebug.next's ajax view in the console is horrible

### ISSUE THREAD

**Issue by trichins** [firebug/firebug.next#180]
In firebug, ajax calls are logged to the console (if you have the setting turned on) and clicking on the call will expand it and let you view the request using the same view as in the Network tab.

Firebug.next is similar to the developer tools and instead of expanding it, it opens it up in a popup that is pretty difficult to read.  It also doesn't format json reponses nicely (it does in the Network panel but not the Inspector panel)

Firebug.next also shows all network traffic in the Inspector panel instead of just ajax calls.  It would be nice to limit to just ajax calls like it is in firebug.

**Comment by fflorent** [comment]
@janodvarko Could be worth to share the xpi so people could share their feedback. What do you think?

Florent

**Comment by janodvarko** [comment]
Yes, I'll release alpha 8

Honza

**Comment by janodvarko** [comment]
$fixed firebug-3.0.0-alpha.8
