### ISSUE TITLE
script searching in firebug.next doesn't support the enter key

### ISSUE THREAD

**Issue by trichins** [firebug/firebug.next#182]
In firebug, I can enter a string to search for and hit enter and it will take me to the first occurrence.  Hitting enter again will take me to the next occurrence.  This lets me quickly loop through the various occurrences.

In firebug.next, hitting enter doesn't seem to do anything.

**Comment by janodvarko** [comment]
Bugzilla report is there and it need to be fixed on the platform.

Honza
