### ISSUE TITLE
Reimplement the auto-completion for the Command Editor

### ISSUE THREAD

**Issue by fflorent** [firebug/firebug.next#184]
Firebug 2 used to have the auto-completion, which is pretty powerful. We should have it back in firebug.next.

Florent

**Comment by janodvarko** [comment]
This needs to be implemented on the platform.
Honza

**Comment by fflorent** [comment]
Wait, do they really have a command editor on the platform? 

Florent

**Comment by janodvarko** [comment]
> Wait, do they really have a command editor on the platform? 

Not yet, but it's one of the top priority features planed.
If you want to work on this, please create a bug report in bugzilla.
Or do you want me to keep this open?

Honza

**Comment by fflorent** [comment]
No, that's fine after what you said.

Florent
