### ISSUE TITLE
No search on the Network panel

### ISSUE THREAD

**Issue by bmoers** [firebug/firebug.next#204]
very useful in the 2x release, please bring back to .next

**Comment by fflorent** [comment]
@bmoers it should be fixed now: 
* in version beta1, it appears at the bottom left of the panel
* in the next beta version, it will appear at the top (fixed with #434)

Shall I close the issue?

Thanks!
Florent

**Comment by janodvarko** [comment]
Comment above is correct, closing.

Honza
