### ISSUE TITLE
Persist button missing in network panel

### ISSUE THREAD

**Issue by mattwoolnough** [firebug/firebug.next#206]
The network persistence option is missing.
Is this due to the functionality not being present in Firefox Developer Tools, or is there another way to achieve the same outcome? 
Screenshot from Firebug 2 below. 
![screen shot 2014-11-20 at 11 25 19 am](https://cloud.githubusercontent.com/assets/9686262/5118034/f22c588a-70a7-11e4-95f5-a6610956a27d.png)

**Comment by SebastianZ** [comment]
> Is this due to the functionality not being present in Firefox Developer Tools, or is there another way to achieve the same outcome?

The DevTools have an option for that under the options panel (the gear icon) called *Enable persistent logs*, which controls this.

Sebastian

**Comment by janodvarko** [comment]
There is now "Persist" button on the Net panel's toolbar.

Thanks for the report.
Honza

**Comment by janodvarko** [comment]
(firebug.sdk changed too)

Honza
