### ISSUE TITLE
Add Events side panel to Inspector panel

### ISSUE THREAD

**Issue by ericnilo** [firebug/firebug.next#216]
Please add the *Events* side panel within the Inspector panel back.

**Comment by janodvarko** [comment]
Agree with the last comment now. In any case, any other UI supporting event handlers should be implemented on the platform.

Honza

**Comment by SebastianZ** [comment]
Florent reported this as [bug 1226640](https://bugzilla.mozilla.org/show_bug.cgi?id=1226640).

Sebastian
