### ISSUE TITLE
Allow disabling events

### ISSUE THREAD

**Issue by fflorent** [firebug/firebug.next#222]
In Firebug 2.0, we used to allow disabling events. It would be nice to have this feature back. 
I guess that's something that should be implemented DevTools side, right?

Florent

**Comment by janodvarko** [comment]
> I guess that's something that should be implemented DevTools side, right?

yes 

Honza

**Comment by SebastianZ** [comment]
Florent reported this as [bug 1226637](https://bugzilla.mozilla.org/show_bug.cgi?id=1226637).

Sebastian
