### ISSUE TITLE
The strikethrough showing a style is overridden makes it hard to see the overridden style w/ dark theme

### ISSUE THREAD

**Issue by MikeHoffert** [firebug/firebug.next#228]
Here's what the strikethrough looks like in Firefox DE's dark theme:

![capture](https://cloud.githubusercontent.com/assets/979790/5271255/1b013e62-7a38-11e4-856e-4bb69bb5a59f.JPG)

It's very difficult to read the disabled text. Perhaps a thinner strikethrough or showing the style is disabled by graying the text would be a better approach? Or perhaps something configurable if theme compatibility is an issue.

**Comment by janodvarko** [comment]
This should be reported on the platform (Firefox)
https://bugzilla.mozilla.org/enter_bug.cgi

Honza
