### ISSUE TITLE
Reimplement "Use in Command Line"

### ISSUE THREAD

**Issue by SystemDisc** [firebug/firebug.next#230]
https://getfirebug.com/wiki/index.php/$p

I use this all the time in the old (current) Firebug. Where did this feature go? If I have my code use console.log(variable), I want to be able to right click on the output and assign it to $p. This is especially helpful with objects. The properties panel is nice, but it's not as versatile as assigning $p to the object you're inspecting.

**Comment by SystemDisc** [comment]
Is anything being done with this?

**Comment by fflorent** [comment]
That's definitely the kind of feature I'd personally like to see in
Firebug.next, and probably one of which I miss the most.

@simonlindholm : if that's feasible, do you want to take that issue ?

Florent

**Comment by fflorent** [comment]
To do so, we would like to extend the bindings set in JSTermHelpers here:
https://dxr.mozilla.org/mozilla-central/source/toolkit/devtools/webconsole/utils.js#1524

We need platform support.

Florent

**Comment by simonlindholm** [comment]
I don't know, I bet we could put things in `_jstermHelpersCache` when "Use in Command Line" is picked. The larger problem I suspect will be that devtools don't have such a unified rep system as firebug.old, but we'll need to patch this feature into places one by one. Although, I guess it wouldn't hurt to start with objects logged to the console, that's probably the most used thing. Hmm.

I *might* take a look at things, if I find time for Firebug, but I can't promise that. Sorry about responding so late.

**Comment by fflorent** [comment]
That would require to change a private property (so that's hackish) and ensure to trigger autocompletion before...

I reported a bug platform-side to allow extending the commands: https://bugzilla.mozilla.org/show_bug.cgi?id=1143497

Florent

**Comment by simonlindholm** [comment]
Hm, wait, I probably misread the code - it would be `_getJSTermHelpers` that we'd need to monkey-patch. Either way, yes, it's hackish (but one can be careful, and unit tests help), but it would work. The property wouldn't show up in auto-completion, but that's okay for this use-case.

**Comment by janodvarko** [comment]
This needs to be fixed on the platform.

Honza

**Comment by simonlindholm** [comment]
And indeed to some extent has been: https://bugzilla.mozilla.org/show_bug.cgi?id=1025778
