### ISSUE TITLE
Object properties not listed on $X

### ISSUE THREAD

**Issue by SystemDisc** [firebug/firebug.next#231]
Steps to reproduce:
- Select an element in the inspector
- Type `$0.`
- There's no list of properties

A way I found around this
- Select an element in the inspector
- `test = $0`
- Type `test.`
- There is now a list of properties

If Firebug is smart enough to realize what `test` is (`test` is a reference to `$0` which is a reference to an element in the DOM), why doesn't it realize what `$0` is?

**Comment by janodvarko** [comment]
Yes, this needs to  be implemented on the platform.

Please, create a report (just copy paste is fine) in: in https://bugzilla.mozilla.org/

Honza
