### ISSUE TITLE
Create a "2.0-gap" label for Github issues

### ISSUE THREAD

**Issue by fflorent** [firebug/firebug.next#233]
The label I often miss is "firebug-gap" or "2.0-gap" for Github issues. These kind of issues are not enhancements nor bugs.

@janodvarko what do you think?

Florent

**Comment by janodvarko** [comment]
I think that all firebug-gaps issues should be directly reported in Bugzilla, so we don't need that flag.
Closing.

@fflorent please shout out if you don't agree.

Honza
