### ISSUE TITLE
Reimplement "use regular expression" in the search box

### ISSUE THREAD

**Issue by fflorent** [firebug/firebug.next#235]
Firebug 2.0 has the "Use Regular Expression" option for the search box in these panels:
1. HTML
2. Script
3. CSS (not working correctly, see [issue 4622](https://code.google.com/p/fbug/issues/detail?id=4622))
4. Net (not working correctly, see [issue 4622](https://code.google.com/p/fbug/issues/detail?id=4622))

It is also probably worthy to implement for every panels (note that a user reported [he missed the feature for the Net panel](https://groups.google.com/forum/#!topic/firebug/Z1qkboqLepw) in Firebug 2.0).

Florent

**Comment by janodvarko** [comment]
This should be implemented on the platform.

Honza
