### ISSUE TITLE
Searching in inspector panel changes number of files in debugger panel

### ISSUE THREAD

**Issue by trichins** [firebug/firebug.next#237]
Steps to reproduce:

1. Go to nightly.mozilla.org
2. Open Firebug
  => It should have the Inspector panel open.  If it doesn't, switch to Inspector panel, close Firebug, reload the page, start at step 1 again
3. Search for "asdf"
  => The search bar should get a red border because nothing was found
4. Switch to debugger panel
5. It shows only 3 files (jquery-1.4.4.js, nightly.js, ga.js)

If you skip step 3, then you'll see 5 files (nav-main.js and nightly.mozilla.org are added).

**Comment by janodvarko** [comment]
Since this is a platform issue I am closing this report.

Honza
