### ISSUE TITLE
DOM tab missing on non firebug theme

### ISSUE THREAD

**Issue by rengaw83** [firebug/firebug.next#239]
When i change the theme to dark or light, the DOM tab are missing. Whenn i swicth back to the Firebug theme, the tab is back.

I am using the current firefox aurora 36.0a2 (2014-12-09) and the firebug 3.0.0-alpha5.

**Comment by janodvarko** [comment]
> Then I change theme back to Light Theme.
> I can use Firebug's DOM feature in light theme.

Yep, this is a bug, thanks for noticing!
(patch committed, see above auto-generated-comment)

Can you please test it?
You can git clone and generate xpi using jpm xpi
See also: https://github.com/firebug/firebug.next#hacking-on-firebugnext-aka-firebug-3

Honza

**Comment by Negaihoshi** [comment]
Confirmed.
This Bug is fixed.

**Comment by janodvarko** [comment]
Thanks for the update!

Honza

**Comment by esphen** [comment]
@janodvarko I must humbly disagree with the decision to only have firebug features in the firebug theme. When you install an addon, you don't expect to have to change the theme of the developer tools to use it, right (or the entire browser when on developer ed.)? Would it not be better to give people the freedom of choice, and have them deactivate the addon if they don't want firebug features?

**Comment by janodvarko** [comment]
@esphen: we'll be yet re-iterating this decision soon, so this might change...
Thanks for the feedback!

Honza

**Comment by janodvarko** [comment]
$fixed firebug-3.0.0-alpha.7

Honza
