### ISSUE TITLE
:hover, :active, :focus - styles

### ISSUE THREAD

**Issue by panayotov90** [firebug/firebug.next#247]
:hover, :active, :focus - styles are missing or i can't find them,

If they are not missing can you tell me were to find them?

**Comment by karlwilbur** [comment]
Yes, definitely missing. Is there a way to get them back? I see that they are there on some sites but not others.
![screenshot from 2015-05-22 20 33 33](https://cloud.githubusercontent.com/assets/55618/7781696/2f68f564-00c2-11e5-86a6-43802762496f.png)

**Comment by fflorent** [comment]
@karlwilbur you will find them in the context menu of an element: 
![screenshot1](https://cloud.githubusercontent.com/assets/371705/7783243/30bb1b30-013b-11e5-8c1e-0ea4657a52e8.png)

Florent

**Comment by janodvarko** [comment]
This should be implemented on the platform. Can someone create a report in https://bugzilla.mozilla.org/ and cross post the link here?

Thanks
Honza
