### ISSUE TITLE
Side panel tab tooltip doesn't work

### ISSUE THREAD

**Issue by janodvarko** [firebug/firebug.next#249]
1. Open the toolbox
2. Select the Style Editor panel and Media Rules side panel
3. Hover mouse over the side panel tab
4. There should be a tooltip displayed (just like for a main panel), but none is visible -> BUG

Honza

**Comment by janodvarko** [comment]
(just reassigning anurag90x is now FWG member)

Honza

**Comment by fflorent** [comment]
\o/

Florent

**Comment by janodvarko** [comment]
$fixed firebug-3.0.0-alpha.7
