### ISSUE TITLE
Put back the colors for the Reps

### ISSUE THREAD

**Issue by fflorent** [firebug/firebug.next#250]
In Firebug 2, strings used to be printed in red, Objects in green, ...:
![firebug_2 0_reps](https://cloud.githubusercontent.com/assets/371705/5560886/5460c28a-8db2-11e4-9efc-f8e71750649d.png)

In Firebug 3.0, the Reps have not those colors anymore:
![firebug_3 0_reps](https://cloud.githubusercontent.com/assets/371705/5560888/8fb99d98-8db2-11e4-86ae-60641fa35b8f.png)

Florent

**Comment by aliuk2012** [comment]
@fflorent I spoke to @janodvarko about where ebst to place the css. I have done part of the fix and will make a pull request soon. We can then discuss this and see if this is the best way to implement.

**Comment by aliuk2012** [comment]
I've managed to get the object styled (See screenshot below)  (3ad7be55fe2dc311bae11715973fb946020d63ad) 
 and I am working on the strings colours. I've picked up another issue which I'll be creating shortly which might explain this plain text style we getting now.

Are we looking to style it like existing Firebug 2+?
![screen shot 2015-01-19 at 21 31 56]
(https://cloud.githubusercontent.com/assets/3441519/5808195/c94227d8-a022-11e4-838a-10ee7bccf7ee.png)

**Comment by janodvarko** [comment]
Nice

> Are we looking to style it like existing Firebug 2+?

Yes

Honza

**Comment by janodvarko** [comment]
Merged in to the master at:
https://github.com/firebug/firebug.next/commit/fd8cf957eadd8317fa5095a8e06a3fb4842dd57a

Honza

**Comment by janodvarko** [comment]
$fixed firebug-3.0.0-alpha.9

http://getfirebug.com/releases/firebug/3.0/firebug-3.0.0-alpha.9.xpi

Honza
