### ISSUE TITLE
Computed side panel is empty

### ISSUE THREAD

**Issue by anurag90x** [firebug/firebug.next#255]
Firebug.next seems to produce an empty computed properties panel when run on Nightly and DevEd.

![screen shot 2015-01-02 at 12 29 40 pm](https://cloud.githubusercontent.com/assets/1813816/5594675/1a5d571a-927b-11e4-846d-ff8df445131e.png)

Changing themes does not seem to help. If however, I run Nightly without firebug then devtools does produce results.

**Comment by fflorent** [comment]
The bug was not present in 44770e43, so there is an opportunity to bisect the commits.

As agreed on IRC, @anurag90x is working on the fix

Florent

**Comment by janodvarko** [comment]
> https://github.com/firebug/firebug.next/pull/256#issuecomment-68527211

@anurag90x again, great analyses!

I have reported a platform bug + a patch. Let' see what Patrick says.
https://bugzilla.mozilla.org/show_bug.cgi?id=1118236

Honza

**Comment by janodvarko** [comment]
I am closing this one. The platform fix can be done independently.

Anyone willing to write a test?

Honza

**Comment by anurag90x** [comment]
I'll add in the test. It should just check that the computed panel isn't empty, correct?

**Comment by janodvarko** [comment]
Yes

**Comment by janodvarko** [comment]
$fixed firebug-3.0.0-alpha.7
