### ISSUE TITLE
FBTrace reporting "The character encoding of the HTML document was not declared?

### ISSUE THREAD

**Issue by aliuk2012** [firebug/firebug.next#259]
If you run jpm test and pass in a profile(I know theres no real need to pass in a profile) that has FBTrace it will log the following error:
>Console Service ERROR [JavaScript Error: "The character encoding of the HTML document was not >declared. The document will render with garbled text in some browser configurations if the document >contains characters from outside the US-ASCII range. The character encoding of the page must be >declared in the document or in the transfer protocol." {file: "http://localhost:8099/test.html" line: 0}] 
>[JavaScript Error: "The character encoding of the HTML document was not declared. The document will >render with garbled text in some browser configurations if the document contains characters from >outside >the US-ASCII range. The character encoding of the page must be declared in the document or >in the transfer protocol." {file: "http://localhost:8099/test.html" line: 0}]

I have fixed the issue and will be submitting a pull request later.
![screen shot 2015-01-07 at 07 29 12](https://cloud.githubusercontent.com/assets/3441519/5642438/7d4cd250-9641-11e4-9afe-099e182eb3ab.png)

**Comment by aliuk2012** [comment]
Screenshot when the patch is applied 
![screen shot 2015-01-07 at 07 52 16](https://cloud.githubusercontent.com/assets/3441519/5642478/4208734c-9642-11e4-9170-59504477f3c7.png)

**Comment by janodvarko** [comment]
$fixed firebug-3.0.0-alpha.7
