### ISSUE TITLE
JavaScript Warning: "SyntaxError: test for equality (==) mistyped as assignment (=)?

### ISSUE THREAD

**Issue by aliuk2012** [firebug/firebug.next#263]
When I runs tests I noticed the following error:

>$ jpm test -b /Applications/FirefoxNightly.app
>JPM info Starting jpm test on Firebug
>JPM info XPI created at  /var/folders/f4/l8tl_fcj169_h0f_zx8jblbh0000gn/T/firebug@software.joehewitt.com.xpi (778ms)
>JPM info Creating a new profile
>JPM info console.log: firebug: [JavaScript Warning: "SyntaxError: test for equality (==) mistyped as >assignment (=)?" {file: "resource://gre/modules/addons/XPIProvider.jsm -> >jar:file:///var/folders/f4/l8tl_fcj169_h0f_zx8jblbh0000gn/T/21ebd6eb-0edf-4ec5-867d->6a4d897fd794/extensions/firebug@software.joehewitt.com.xpi!/bootstrap.js -> >resource://gre/modules/commonjs/toolkit/loader.js -> resource://firebug-at-software-dot-joehewitt-dot->com/lib/core/domplate.js" line: 795 column: 25 source: "  while (m = re.exec(str))
>"}]

As you can see the syntax error is occurring in domplate.js line 795. To me this looks like a logical error in that in the while loop we are assigning re.exec(str) value to the variable m but we not evaluating it. There appears to be other various files that are reporting that same console.log

I do have a simple solution to this which I will submit shortly for some comments. If we agree to the changes I'll be happy to replicate across all the various files that are reporting this error.

**Comment by simonlindholm** [comment]
Honestly I think we should just turn off `javascript.options.strict` when running through jpm; it doesn't seem to be very valuable.

**Comment by aliuk2012** [comment]
Have is the fix I was mentioning, 2e72ebd004d89aaf325d666033d43632f1f0daf7

**Comment by simonlindholm** [comment]
Looks good to me, FWIW, I'd say you can commit that. (Although I still don't see much point in strict warnings.)

**Comment by janodvarko** [comment]
Looks good to me too. Please merge.

I am not sure about the string warnings, my gut feeling is that they could be useful and reveal things to fix, no?

Honza

**Comment by janodvarko** [comment]
$fixed firebug-3.0.0-alpha.7
