### ISSUE TITLE
Inclusion of add-SDK in the readme

### ISSUE THREAD

**Issue by aliuk2012** [firebug/firebug.next#264]
Is there particular reason why the first part of readme suggests you download Add-on SDK?  A part from using the latest and greatest version. I know its included in Firefox nightly and it depends how frequently they update their version of the SDK. You can obviously just run JPM without using the -o <path to your local version of sdk>

**Comment by janodvarko** [comment]
Good catch, readme file fixed.

Thanks for the report!

Honza

**Comment by janodvarko** [comment]
$fixed firebug-3.0.0-alpha.7
