### ISSUE TITLE
No fixed issues found for Firebug 3 alpha 6

### ISSUE THREAD

**Issue by janodvarko** [firebug/firebug.next#266]
No issues found for Firebug 3 alpha 6:
http://issues.firebug.io/tagged/fixed/firebug-3.0.0-alpha.6

Even if there is at least one:
https://github.com/firebug/firebug.next/issues/188

Link used in release notes:
https://github.com/firebug/firebug.next/blob/master/release-notes.md

Honza

**Comment by janodvarko** [comment]
@cadorn: any ideas?

Honza

**Comment by cadorn** [comment]
will check shortly

**Comment by cadorn** [comment]
Fixed.

Issues scraper was in an unrecoverable state. Looking forward to having backend logs to track this stuff.

**Comment by janodvarko** [comment]
Works for me now, thanks!
Honza

**Comment by janodvarko** [comment]
No issues found:
http://issues.firebug.io/tagged/fixed/firebug-3.0.0-alpha.7
(e.g. https://github.com/firebug/firebug.next/issues/264)

Honza

**Comment by cadorn** [comment]
hmm. looks like I need to take a better look. fixed for now.

**Comment by janodvarko** [comment]
Works now, thanks!
Honza

**Comment by janodvarko** [comment]
The same problem for alpha 9:
http://issues.firebug.io/tagged/fixed/firebug-3.0.0-alpha.9

Honza

**Comment by cadorn** [comment]
fixed.

**Comment by janodvarko** [comment]
Thanks!
Honza
