### ISSUE TITLE
The source in the Debugger panel doesn't appear when breaking on reload

### ISSUE THREAD

**Issue by fflorent** [firebug/firebug.next#273]
STR:
1. Open this page: https://www.mozilla.org/en-US/contribute/
2. Open Firebug on it
3. Put a Breakpoint at line 74 of tabzilla.js
4. Reload the page
=> The execution should break on this line
=> But the source of tabzilla.js is not displayed

![Debugger panel without source](https://cloud.githubusercontent.com/assets/371705/5782547/5f1b24a8-9dbc-11e4-8144-ebed53f6181b.png)

Florent

**Comment by janodvarko** [comment]
Thanks for the report!

Does it work for you now?

Honza

**Comment by fflorent** [comment]
Works like a charm! Thanks!

Florent

**Comment by janodvarko** [comment]
Excellent, thanks for verification!
Honza

**Comment by janodvarko** [comment]
$fixed firebug-3.0.0-alpha.8
