### ISSUE TITLE
The "disable browser cache" option doesn't work

### ISSUE THREAD

**Issue by fflorent** [firebug/firebug.next#275]
STR:
1. Open this page: https://www.mozilla.org/en-US/contribute/
2. Open Firebug, switch to the Network panel
3. Check the "disable browser cache" option
4. Reload
    => There are some request still being in cache (Status code 304)

Florent

**Comment by fflorent** [comment]
Originally reported in issue #198 

Florent

**Comment by Mahks** [comment]
I had to disable "Show original sources" in debugger options, as well, to stop caching.

**Comment by janodvarko** [comment]
Nice catch, does it work for you now?

Honza

**Comment by janodvarko** [comment]
$fixed firebug-3.0.0-alpha.8
