### ISSUE TITLE
Debugger's location panel not showing pointer 

### ISSUE THREAD

**Issue by aliuk2012** [firebug/firebug.next#276]
Go to the debugger panel, move over the individual files that are loaded in. There is no 'pointer' shown to suggest that you can click on it link other links. I think this should be a pointer so its consistent across Firebug. Look at the Style Editor location panel and you will thats is how it also works.

**Comment by janodvarko** [comment]
The patch works for me, you can merge it into the master.

Btw. the selected source should use light gray background (the same as e.g. the Network panel).
Can you please also fix that? (you can do that as part of separate issue).

Thanks
Honza

**Comment by janodvarko** [comment]
> Btw. the selected source should use light gray background (

Ah, already reported here:
https://github.com/firebug/firebug.next/issues/278

Honza

**Comment by janodvarko** [comment]
> The patch works for me, you can merge it into the master.

The pull request merged.

Honza

**Comment by aliuk2012** [comment]
If the pull request is done can we close this or is there a particular reason why this one is still open?

**Comment by fflorent** [comment]
Yep. You can reference the pull request and close it.

Pull request merged: #282 

Florent

**Comment by janodvarko** [comment]
$fixed firebug-3.0.0-alpha.8
