### ISSUE TITLE
Highlight the selected source in the debugger panel

### ISSUE THREAD

**Issue by fflorent** [firebug/firebug.next#277]
Currently, there is only an arrow showing which source is selected:
![selected_location](https://cloud.githubusercontent.com/assets/371705/5793101/0ebc5752-9f38-11e4-9b43-35ce99bacac7.png)

But at a first glance, that's not clear. I think we should highlight a bit, like the DevTools do:
![selected_location_devtools](https://cloud.githubusercontent.com/assets/371705/5793105/46b32f64-9f38-11e4-9340-a4a7fed860ab.png)

Florent

**Comment by aliuk2012** [comment]
If everyone is happy with this suggestion, i'll be happy to implement

**Comment by janodvarko** [comment]
Yep this would be great to have!

Honza

**Comment by janodvarko** [comment]
I think we should use the same background color as the Network panel for selected entry.
Honza

**Comment by fflorent** [comment]
What about also putting the location in bold?

Florent

**Comment by fflorent** [comment]
>If everyone is happy with this suggestion, i'll be happy to implement
Then I assign @aliuk2012 to this issue.

Florent

**Comment by aliuk2012** [comment]
fixed as part of commit 8848d9ef9c8073d4c37a50a6d57b9b592a6d6c33 and related to issue #286

**Comment by janodvarko** [comment]
$fixed firebug-3.0.0-alpha.8
