### ISSUE TITLE
The location of the selected source is invisible

### ISSUE THREAD

**Issue by fflorent** [firebug/firebug.next#278]
STR:
1. Go to https://www.mozilla.org/en-US/contribute/
2. Open the Debugger panel of Firebug
3. Select site-min.js (or other black boxed source)
    => The location is not readable
![selected_blackboxed_location1](https://cloud.githubusercontent.com/assets/371705/5793203/8219adfa-9f3b-11e4-9a88-0b5ebc403c93.png)

Also reported for the DevTools here: https://bugzilla.mozilla.org/show_bug.cgi?id=1122733

Florent

**Comment by janodvarko** [comment]
@anurag90x  interested in this one? ;-)

Honza

**Comment by anurag90x** [comment]
Sure  I'll take it

**Comment by aliuk2012** [comment]
@anurag90x how far are you with this? I have resolved this as part of #286 basically its because the text colour is white and the background colour is not being set through a variable.

**Comment by aliuk2012** [comment]
Fixed as part of commit 8848d9ef9c8073d4c37a50a6d57b9b592a6d6c33 and related to issue #286

**Comment by fflorent** [comment]
Yep, though it remains hard to read. I will fill another issue for this.

Florent

**Comment by aliuk2012** [comment]
I think you getting confused with #279 which is still open and relates to black sourced locations being hard to read, Maybe just mention it in that issue

**Comment by fflorent** [comment]
Oh, your right :). No other issue then!

Florent

**Comment by fflorent** [comment]
Hmm, I am wrong to say that you're right. Issue #279 targeted the non-selected locations (but the issue might be corrected together with it).

Florent

**Comment by janodvarko** [comment]
$fixed firebug-3.0.0-alpha.8
