### ISSUE TITLE
The location of the blackboxed source are difficult to read

### ISSUE THREAD

**Issue by fflorent** [firebug/firebug.next#279]
STR:
1. Open this page: https://www.mozilla.org/en-US/contribute/
2. Open Firebug, switch to the Debugger panel

The source location of the blackboxed source are difficult to read (especially for low-sight and probably color blind people).

Note: not talking about the selected location, whose issue is already reported here in issue #278.
![non selected blackboxed source are difficult to read](https://cloud.githubusercontent.com/assets/371705/5966129/fba05d80-a801-11e4-9ead-1a1da09ee58b.png)

Florent

**Comment by bmdeveloper** [comment]
I am happy to have a look at this

**Comment by janodvarko** [comment]
@fflorent: isn't this already fixed by #286?
I can't tell from the test case, I don't see any black boxed sources

Honza

**Comment by fflorent** [comment]
@janodvarko No it isn't. It's just that the test case was wrong. I also updated the screenshot so it is more clear.

Florent

**Comment by janodvarko** [comment]
@fflorent: OK, I see it now.
@bmdeveloper: great!

My comments:
1. The text (of black boxed source) should be 'gray'
2. It should be 'black' when selected.
3. Styles should be put into chrome/skin/classic/shared/debugger.css (the /* Sources Panel */ section)

Honza





Honza

**Comment by aliuk2012** [comment]
It is already 'grey' , perhaps a darker darker grey? 
 
![screen shot 2015-02-02 at 16 37 52](https://cloud.githubusercontent.com/assets/3441519/6004326/ed3a0f98-aaf9-11e4-9cbc-1867934c77fa.png)

Below is an example of a "selected" one that is black boxed:
![screen shot 2015-02-02 at 16 37 35](https://cloud.githubusercontent.com/assets/3441519/6004325/ed384dc0-aaf9-11e4-8908-58c43374451e.png)

the original screenshot @fflorent posted did not have a blue background which is why you couldn't see the filename just above the red border which was fixed in #286

**Comment by janodvarko** [comment]
> It is already 'grey' , perhaps a darker darker grey? 
Ah, true, agree something darker e.g. rgb(81,81,81)?

> the original screenshot @fflorent posted did not have a blue background which is
> why you couldn't see the filename just above the red border which was fixed in #286
I see, nice

Honza

**Comment by fflorent** [comment]
> Ah, true, agree something darker e.g. rgb(81,81,81)?

Yep, let's give it a try. Another thing I think would be nice to have is a logo at the left of the source file (like a stroke eye, that used to be there before). If we do that, we may change the "disabled source" logo of the Style Editor panel. 

What do you think?

Florent

**Comment by janodvarko** [comment]
Do you have some screenshots/mockups? I am not sure what logos do you have in mind.

Honza

**Comment by bmdeveloper** [comment]
I have made the colour changes and created a pull request

**Comment by janodvarko** [comment]
Pull merged at https://github.com/firebug/firebug.next/commit/93fd6ed0112bb06db136a1de169ea18aaa1318c2

Thanks!

Honza

**Comment by janodvarko** [comment]
$fixed firebug-3.0.0-alpha.9

http://getfirebug.com/releases/firebug/3.0/firebug-3.0.0-alpha.9.xpi

Honza
