### ISSUE TITLE
Buttons of the Timeline panel not visible

### ISSUE THREAD

**Issue by fflorent** [firebug/firebug.next#280]
The buttons "Record timeline operations" and "Select what data to display" of the Timeline panel are not displayed correctly:
![timeline panel](https://cloud.githubusercontent.com/assets/371705/5793237/c47b35dc-9f3c-11e4-9331-f7e7dcc1112d.png)

Florent

**Comment by fflorent** [comment]
@janodvarko the above patch fixes the issue. Is that OK for you?

Florent

**Comment by fflorent** [comment]
ping @janodvarko ?

Florent

**Comment by janodvarko** [comment]
@fflorent works for me. Please merge to the master, thanks!
Honza

**Comment by fflorent** [comment]
Thanks for the verification. That's merged now.

Florent

**Comment by janodvarko** [comment]
$fixed firebug-3.0.0-alpha.8
