### ISSUE TITLE
Pressing a filter button in the Network panel displays a red cross

### ISSUE THREAD

**Issue by fflorent** [firebug/firebug.next#281]
Even if donating to the [Red Cross](https://en.wikipedia.org/wiki/International_Committee_of_the_Red_Cross) is a good action, it sounds inappropriate to display subliminal message for this in the network panel :)

STR:
1. Open Firebug on this page
2. Switch to the Network panel
3. Press a filter button or the "Clear" / "Export" buttons
    => A red cross appear in place of the pressed button

![selected_blackboxed_location1](https://cloud.githubusercontent.com/assets/371705/5793267/f4363ed8-9f3d-11e4-89a3-68bf704b89ec.png)

Florent

**Comment by fflorent** [comment]
Should be fixed with the above commit.

Florent

**Comment by janodvarko** [comment]
$fixed firebug-3.0.0-alpha.8
