### ISSUE TITLE
Inspector side panels toolbar and main panel toolbar are misaligned

### ISSUE THREAD

**Issue by SebastianZ** [firebug/firebug.next#284]
The *Inspector* side panels toolbar is 1px higher than the main panel toolbar. Tested with FF 38.0a1 (2015-01-18) + FB 3.0.0-alpha.7 on Win7.

![Misaligned side panels toolbar](https://cloud.githubusercontent.com/assets/958943/5797616/e05de19c-9fbd-11e4-9c82-2c6270f6ebbc.png)

Sebastian

**Comment by janodvarko** [comment]
@anurag90x  Anurag, interested to take a look a t this one?

Honza

**Comment by bmdeveloper** [comment]
I am good to have a look at this one as well

**Comment by janodvarko** [comment]
OK, assigned to you

Honza

**Comment by janodvarko** [comment]
The pull request merged, thanks!
Honza

**Comment by janodvarko** [comment]
$fixed firebug-3.0.0-alpha.8
