### ISSUE TITLE
Command Editor buttons are not displayed

### ISSUE THREAD

**Issue by SebastianZ** [firebug/firebug.next#285]
The Command Editor is missing its buttons within the toolbar.

![Missing Command Editor buttons](https://cloud.githubusercontent.com/assets/958943/5797681/eece436a-9fbe-11e4-888c-e72983614711.png)

Sebastian

**Comment by fflorent** [comment]
Also the buttons at the bottom (Run, Clear, ...).

Looks like a regression due to some update in Nightly. mozregression seems to be the good tool for that job.

Florent

**Comment by aliuk2012** [comment]
mozregression looks interesting. might help explain why our build is failing since last thursday.

**Comment by janodvarko** [comment]
Fixed at https://github.com/firebug/firebug.next/commit/6e1e8d66962a6a1bea2126d0ad90f6fb0a50dfc2

Does it work for you now?

Honza

**Comment by janodvarko** [comment]
One more commit related to the Inspector side panels.
Honza

**Comment by janodvarko** [comment]
$fixed firebug-3.0.0-alpha.8
