### ISSUE TITLE
Firebug not using the css var values:

### ISSUE THREAD

**Issue by aliuk2012** [firebug/firebug.next#286]
When I've been looking at issue #250 I noticed that firebug doesn't use/interpret the css var values. Having done a search through all the plugins files I cannot locate these values which might be why the styling is all plain and black,

Also when you run jom test you will see quiet a few console.log around this:
>JPM info console.log: firebug: [JavaScript Warning: "Property contained reference to invalid variable.  >Error in parsing value for 'border-right-color-ltr-source'.  Falling back to 'initial'." {file: "chrome://browser/skin/devtools/webconsole.css" line: 506 column: 10316 source: " var(--theme-body-background)"}]
console.log: firebug: [JavaScript Warning: "Property contained reference to invalid variable.  Error in parsing value for 'border-right-color-rtl-source'.  Falling back to 'initial'." {file: "chrome://browser/skin/devtools/webconsole.css" line: 506 column: 10316 source: " var(--theme-body-background)"}]
console.log: firebug: [JavaScript Warning: "Property contained reference to invalid variable.  Error in parsing value for 'background-color'.  Falling back to 'initial'." {file: "chrome://browser/skin/devtools/webconsole.css" line: 505 column: 10259 source: " var(--theme-tab-toolbar-background)"}]
console.log: firebug: [JavaScript Warning: "Property contained reference to invalid variable.  Error in parsing value for 'color'.  Falling back to 'inherit'." {file: "chrome://browser/skin/devtools/webconsole.css" line: 514 column: 10451 source: " var(--theme-comment)"}]
console.log: firebug: [JavaScript Warning: "Property contained reference to invalid variable.  Error in parsing value for 'color'.  Falling back to 'inherit'." {file: "chrome://browser/skin/devtools/webconsole.css" line: 510 column: 10386 source: " var(--theme-content-color1)"}]
console.log: firebug: [JavaScript Warning: "Property contained reference to invalid variable.  Error in parsing value for 'color'.  Falling back to 'inherit'." {file: "chrome://browser/skin/devtools/webconsole.css" >line: 510 column: 10386 source: " var(--theme-content-color1)"}]

I'll add in the various vars and see if this helps. Also it might temporary resolve #279  (Although are we looking to reuse a lot of the default styling or looking to give it a firebug style 'touch up').

**Comment by aliuk2012** [comment]
Fixed in commit 8848d9ef9c8073d4c37a50a6d57b9b592a6d6c33 and merged as part of Pull Request #297

**Comment by janodvarko** [comment]
$fixed firebug-3.0.0-alpha.8
