### ISSUE TITLE
Search in DOM panel broken

### ISSUE THREAD

**Issue by janodvarko** [firebug/firebug.next#289]
STR:

1. Open the toolbox on www.google.com
2. Select the DOM panel
3. Type "URL" (no quotes)
4. Nothing is selected in the panel -> BUG

Honza

**Comment by janodvarko** [comment]
Might be related to issue #287 

Honza

**Comment by janodvarko** [comment]
This was simpler than I thought...

Honza

**Comment by fflorent** [comment]
Ahaha :)

Florent

**Comment by janodvarko** [comment]
$fixed firebug-3.0.0-alpha.8
