### ISSUE TITLE
The "remove watch" button of the Debugger is not well displayed

### ISSUE THREAD

**Issue by fflorent** [firebug/firebug.next#290]
STR:
1. Open Firebug on this page: https://getfirebug.com/tests/head/script/debuggerKeyword/testPage.html
2. Switch to the Debugger panel
3. Click on "Debugger simple"
4. Add this watch expression in the "variables" side-panel: "window"
5. Hover your newly created watch expression
    => The cross to remove the watch expression is not much visible

![delete watch expression button hidden](https://cloud.githubusercontent.com/assets/371705/5845971/9907e5cc-a1c0-11e4-9d60-1baeffe4a71b.png)

Florent

**Comment by fflorent** [comment]
Should be

**Comment by janodvarko** [comment]
$fixed firebug-3.0.0-alpha.8
