### ISSUE TITLE
Network panel not active until page loaded

### ISSUE THREAD

**Issue by Mahks** [firebug/firebug.next#294]
Need to activate prior to load so we can see the page loading activity, like in FB2
Note this does work once the network tab has been opened at least once.
But if any other tab is active when FB is opened, then the network panel does not log anything.

**Comment by janodvarko** [comment]
@Mahks why do you need this?

Note, that you can export all the collected data in the Net panel (as HAR file) using HARExportTrigger extension. This extension can export all the data even if the Toolbox isn't open at all!

Read more about this extension here: http://www.softwareishard.com/blog/har-export-trigger/

I am closing this report, but feel free to reopen or explain what is your use case and I can help!

Honza
