### ISSUE TITLE
Typo in skin/classic/mac/scrollbox.css

### ISSUE THREAD

**Issue by aliuk2012** [firebug/firebug.next#298]
Running jpm test the following message is logged.
>JPM info console.log: firebug: [JavaScript Warning: "Expected end of value but found '3p'.  Error in parsing value for 'padding'.  Declaration dropped." {file: "chrome://firebug-os/skin/scrollbox.css" line: 27 column: 13 source: "  padding: 0 3p 0 3px;"}]

**Comment by janodvarko** [comment]
Merged at https://github.com/firebug/firebug.next/commit/aa4ef79ae21ae1a206651714d9c339d3e36c4007

Thanks for the patch!

Honza

**Comment by janodvarko** [comment]
$fixed firebug-3.0.0-alpha.8
