### ISSUE TITLE
OS-X - Use arrow style for twisties

### ISSUE THREAD

**Issue by thomasandersen** [firebug/firebug.next#30]
See FB2 screenshot for reference.

FB2
![screen shot 2014-07-10 at 00 26 55](https://cloud.githubusercontent.com/assets/194093/3532218/51e27f9c-07b8-11e4-8149-5af722212db0.png)

.next
![screen shot 2014-07-10 at 00 27 52](https://cloud.githubusercontent.com/assets/194093/3532219/572119aa-07b8-11e4-8e04-0197e538e599.png)

**Comment by aliuk2012** [comment]
I'm happy to take a look at this one.  Before I fix this are we going for the 'triangles/twisties' kind of look across all the Operating systems? If so can someone one a windows and linux machine confirm they can see the twisties now. I have a feeling the answer is "No, I'm also getting the boring '+' and '-'" but need some confirmation in what direction we want to take with this styling.

**Comment by fflorent** [comment]
> Before I fix this are we going for the 'triangles/twisties' kind of look across all the Operating systems?

No, this style has always been specific to OS-X. The Firebug theme for Mac is always different to the others in order to fit with the design of the operating system.

Florent

**Comment by aliuk2012** [comment]
Ah, that makes sense,  I could have sworn I saw those twisties on other firebug installation using other OS. Then again it might of just been when I was on my Mac that I'm thinking about. I'll get this one sorted.

**Comment by aliuk2012** [comment]
Issue #308 is the enabler to progress this further. I have the files laid out etc but need help to implement the OS detection feature

**Comment by janodvarko** [comment]
Why do you need isMac() API? This could be done in osx specific CSS file no?
We can create a new file/rules in chrome/skin/classic/mac and override default styles (win) by styles for OSX. Use the same file name for the new OSX style as the file name that contains the rule you want to override.

See this place where OS dependent styles are inserted automatically.
https://github.com/firebug/firebug.next/blob/master/lib/chrome/theme.js#L63

Honza

**Comment by aliuk2012** [comment]
Oh yes, I hadn't thought about including it OS dependent styles.

Although I'm not sure that the OS dependent styles are actually being loaded. I'll create a new branch in the repo and upload my source with comments. I atttempt the DOM panel first and it didn't appear to work but when I included it in the domTree.css as @import "chrome://firefox-os/skin/panel.css it worked but again only partially.

**Comment by janodvarko** [comment]
I think there is a problem with the @import. In any case here is a suggestion:

1. Modify the following chrome manifest line to point to shared dir by dafault
skin firebug-os classic/1.0 chrome/skin/classic/shared/
2. Keep the new twistyOpen, twistyClosed images in mac dir
3. Change panel.css to point to: chrome://firebug-os/skin/twistyClosed.svg

This should be enough to fix this bug.

Honza

**Comment by janodvarko** [comment]
Btw. can you please name branches as issue<#> (no dash). This way it's consistent with all the other branch names :-)

Honza

**Comment by janodvarko** [comment]
$fixed firebug-3.0.0-alpha.8

https://github.com/firebug/firebug.next/releases/tag/firebug-3.0.0-alpha.8

Honza
