### ISSUE TITLE
TypeError: this.panel.hidePopup is not a function

### ISSUE THREAD

**Issue by janodvarko** [firebug/firebug.next#301]
STR:
1. Open the toolbox and load https://getfirebug.com/tests/1.12/net/601/issue601.html
2. Select the Network panel and then the Console panel
3. Click the POST button on the page.
4. Watch the browser console (or FBTrace) there is an exception: 
Console Service ERROR: notify event 'networkEvent' threw an exception: TypeError: this.panel.hidePopup is not a function

resource:///modules/devtools/shared/widgets/Tooltip.js (262)
chrome://browser/content/devtools/netmonitor-view.js (1071)
chrome://browser/content/devtools/netmonitor-view.js (527)
chrome://browser/content/devtools/netmonitor-controller.js (560)
resource://gre/modules/devtools/dbg-client.jsm (190)
resource://gre/modules/devtools/dbg-client.jsm (942)
resource://firebug-at-software-dot-joehewitt-dot-com/lib/debug/transport-hooks.js (43)
resource://gre/modules/devtools/transport/transport.js (545)
resource://gre/modules/devtools/DevToolsUtils.js (82)
resource://gre/modules/devtools/DevToolsUtils.js (82)

The exception doesn't happen if Firebug is disabled

Honza

**Comment by aliuk2012** [comment]
Already been logged #242

**Comment by janodvarko** [comment]
Ah, thanks!

Honza
