### ISSUE TITLE
Add a "Firebug Settings" in Devtools options panel. 

### ISSUE THREAD

**Issue by aliuk2012** [firebug/firebug.next#302]
I think we need to add a "Firebug Settings" section under. A good and obvious place would be to the far right between "Editor Preferences" and "Advanced Settings". 

We can then include options like mentioned in issue #292  and also as part of the fireQuery migration work. We can also perhaps see  or create a API for third party plugin developers to extend these options. 

I would like to look at this issue but I may need some help and pointers, I would appreciate it you could post any links that maybe helpful as part of this issue. I'm busying working through the XUL tutorials to get a better understanding.

**Comment by janodvarko** [comment]
@aliuk2012: can you please move this issue into FireQuery issue list?
https://github.com/firebug/firequery/issues

Honza
