### ISSUE TITLE
Firebug 3.0a6 doesn't update automatically

### ISSUE THREAD

**Issue by fflorent** [firebug/firebug.next#303]
STR from a collegue of mine:
1. Install Firebug 3.0a6
2. Force the update in about:addons of all the addons
   => the update is not done

Florent

**Comment by fflorent** [comment]
Reproduced on my machine:

![no update](https://cloud.githubusercontent.com/assets/371705/5927075/6b3b4bde-a670-11e4-9158-7b1a67c02569.png)

Florent

**Comment by fflorent** [comment]
Ah... I forgot to mention that I used Firefox DevEd (37a*).
And in update.rdf:
````xml
<minVersion>38.0a2</minVersion>
````

@janodvarko What kind of feature is missing in order to support the current DevEd?

Florent

**Comment by janodvarko** [comment]
I set the min version to 37.0a2 so, even the deved is supported.
Update from a6 to a7 works for me now.

@fflorent can you verify?

Honza

**Comment by fflorent** [comment]
Yep. It works.

Florent

**Comment by janodvarko** [comment]
Thanks!
Honza

**Comment by janodvarko** [comment]
$fixed firebug-3.0.0-alpha.8
