### ISSUE TITLE
fireQuery : inject jQuery into the page

### ISSUE THREAD

**Issue by aliuk2012** [firebug/firebug.next#304]
Currently in fireQuery, there is a button on the 'Console' panel that injects the latest version of jQuery into the page if it does not already have jQuery loaded.

![screen shot 2015-01-27 at 20 43 10](https://cloud.githubusercontent.com/assets/3441519/5927162/d78b7cb2-a668-11e4-9c04-6e6f26412b6d.png)

When the user click on it they should get a prompt to say if it has been loaded or if it already has jQuery and the prompt should state the version.

**Injected jQuery message:**
![screen shot 2015-01-27 at 20 51 57](https://cloud.githubusercontent.com/assets/3441519/5926898/73eb7fc4-a666-11e4-8bd4-86497b96c743.png)

**jQuery already used on the page message:**
![screen shot 2015-01-27 at 20 49 27](https://cloud.githubusercontent.com/assets/3441519/5926908/826a8bb2-a666-11e4-88f6-02922db2a03e.png)

Our version should allow the user to choice what version they inject as per the existing fireQuery FAQ sections describes  (Although it would be good to have this as a UI option for those non-technical developers or those whose systems may be restricted to such changes):
![screen shot 2015-01-27 at 20 59 12](https://cloud.githubusercontent.com/assets/3441519/5927039/d0475efe-a667-11e4-850b-f0ec8db651d7.png)

**Enhancement:**
1. Currently after each page refresh the user has to click the 'jQuerify' button to inject jQuery again. Ideally it should remember the state or perhaps have an option to inject it into all webpages.

**Comment by fflorent** [comment]
A bit similar to issue #305. A button to jQuerify would add more discoverability, so I am OK with this feature.

Florent

**Comment by aliuk2012** [comment]
Should it be a button on the console panel as it is now? or should it not be in the console panel menu? or perhaps in the the DevTools Options as a separate 'Firebug Settings' section.

What do you think?

**Comment by janodvarko** [comment]
@aliuk2012 Firequery has its own issue list now. Please report it here:
https://github.com/firebug/firequery/issues

I am cleaning up Firebug.next issue list...

Honza
