### ISSUE TITLE
Reimplement the include() command

### ISSUE THREAD

**Issue by fflorent** [firebug/firebug.next#305]
Firebug 2.0 used to have the `include` command (with aliases):
https://getfirebug.com/wiki/index.php/Include

Florent

**Comment by janodvarko** [comment]
Just like the other missing Command line API this should be implemented on the platform.

Honza

**Comment by SebastianZ** [comment]
This was reported as [bug1164776 ](https://bugzilla.mozilla.org/show_bug.cgi?id=1164776).

Sebastian
