### ISSUE TITLE
Storage tab does not show cookies with a domain in the format ".www.domain.com"

### ISSUE THREAD

**Issue by mattcoz** [firebug/firebug.next#306]
If a cookie is set with a domain value in the format ".www.domain.com", with a dot before the "www", it will not show in the storage tab when visiting "www.domain.com". Firefox has the same problem with the "cookie list" command in the developer toolbar.

**Comment by janodvarko** [comment]
This should be reported in Bugzilla (it's a platform issue)
https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox&component=Developer%20Tools%3A%20Storage%20Inspector

Closing

Honza

**Comment by mattcoz** [comment]
It is reported in Bugzilla, but they don't seem all that interested in fixing it.

https://bugzilla.mozilla.org/show_bug.cgi?id=1126144
