### ISSUE TITLE
Determine what OS the installation is installed on.

### ISSUE THREAD

**Issue by aliuk2012** [firebug/firebug.next#308]
We need a way to determine what OS is being used to load in functionality. 

For example, loading in OS specific css as mentioned in issue #30. I did find that Firebug 2.0 has this file but not sure how much of it can be ported over:

https://github.com/firebug/firebug/blob/master/extension/content/firebug/lib/system.js

**Comment by janodvarko** [comment]
You can use SDK:

````
const runtime = require("sdk/system/runtime");
const isMac = runtime.OS === "Darwin";
````

**Comment by aliuk2012** [comment]
Thanks for that :+1:
