### ISSUE TITLE
Implement per URL activation

### ISSUE THREAD

**Issue by SebastianZ** [firebug/firebug.next#310]
Previous versions of Firebug had their [activation](https://getfirebug.com/wiki/index.php/Activation) based on a per URL basis following the same origin policy instead of opening per tab.

It should be considered to change this functionality back to the old behavior.

**Comment by aliuk2012** [comment]
I think this might be a duplicate issue: #292

**Comment by SebastianZ** [comment]
You're right.

Sebastian
