### ISSUE TITLE
Can't collapse Response Headers (follow-up of #180)

### ISSUE THREAD

**Issue by fflorent** [firebug/firebug.next#311]
STR:
1. Go to https://github.com/firebug/firebug.next/tree/master/chrome
2. Open the Console panel
3. Enable the "log" level for the "Net" filter
4. Click on "locale/en-US"
5. Expand the request for `GET https://github.com/firebug/firebug.next/tree/master/chrome/locale/en-US`
    => The detail is displayed
6. Select the Headers tab
7. Collapse the "Response Headers"
    => Only the "view source" link is hidden

Florent

**Comment by fflorent** [comment]
Follow-up of #180

**Comment by janodvarko** [comment]
Fixed at:
https://github.com/firebug/firebug.next/commit/d6c41b87564c6ba48389383eda921e474fc00b65


Honza

**Comment by janodvarko** [comment]
$fixed firebug-3.0.0-alpha.8
