### ISSUE TITLE
The XHR requests should be displayed by default

### ISSUE THREAD

**Issue by fflorent** [firebug/firebug.next#312]
STR:
0. Ensure to start with a fresh profile
1. Go to https://github.com/firebug/firebug.next/tree/master/chrome
2. Open the Console panel
3. Click on "locale/en-US"

The XHR requests are not displayed by default (to display them, you have to enable the "log" level for the "Net" filter). They should be to be compliant with the Firebug 2.0 behavior. 

Note: this is a follow-up of #180.

Florent

**Comment by janodvarko** [comment]
We can set devtools.webconsole.filter.networkinfo pref to true by default.

Should it happen every time on:
1. install
2. enable

Should we remember the old value and revert when:
1. uninstall
2. disable

?


Honza

**Comment by fflorent** [comment]
Well, doing so would also display the other requests (css, js), whereas we would like to only log the XHRs.

So I would introduce another option for that in the Net filter (probably worth to discuss with the DevTools team).

What do you think?

Florent

**Comment by janodvarko** [comment]
I see, true.

Honza

**Comment by janodvarko** [comment]
I think we should just close this issue, it's not a big deal for the user to flip the Net filter in the Console and also I don't think that Firebug theme should behave differently than the other themes in this case.

@fflorent I am closing this, but please shout out, if you don't agree.

Honza

**Comment by fflorent** [comment]
Agree. I think it has already been reported in some bugzilla issue.

Florent
