### ISSUE TITLE
Firebug 3 alpha 8 reporting no fixed issues

### ISSUE THREAD

**Issue by aliuk2012** [firebug/firebug.next#313]
http://issues.firebug.io/tagged/fixed/firebug-3.0.0-alpha.8 Is reporting no fixed bugs

**Comment by janodvarko** [comment]
@cadorn any clues?

Honza

**Comment by cadorn** [comment]
Argh.

Fixed for now. I'll make it to that part of the system soon and fix this for good.

On the upside this is a good way for me to be aware of new releases ;)

**Comment by janodvarko** [comment]
Works for me now, thanks

:-)

Honza

**Comment by janodvarko** [comment]
@cadorn http://issues.firebug.io/tagged/fixed/firebug-3.0.0-alpha.8 needs an update
(issue #30 marked as fixed, but not in the list)

Honza

**Comment by cadorn** [comment]
Fixed. Just had to restart the service again. I am about to commit a chunk of time to FirePHP for FB 3 and see if I can fix this issue too.
