### ISSUE TITLE
The theme is not applied when opening a private window

### ISSUE THREAD

**Issue by fflorent** [firebug/firebug.next#320]
STR:
1. Open a private window (Ctrl-Shift-P)

=> The theme of the private window is not Australis

Florent

**Comment by janodvarko** [comment]
I can't reproduce the problem. When opening a private window I see Australis theme.
Can you please provide more detailed STR and/or screenshots?

Honza

![issue320](https://cloud.githubusercontent.com/assets/37785/6150771/a2a0a130-b211-11e4-9743-277edfa734ec.jpg)

**Comment by janodvarko** [comment]
@fflorent ?

Honza

**Comment by janodvarko** [comment]
@fflorent?

Honza

**Comment by janodvarko** [comment]
@fflorent this seem to be working for me.
Please reopen if you see any issues.

Honza

**Comment by fflorent** [comment]
Sounds it has been fixed, indeed :).

Florent
