### ISSUE TITLE
copy() in the console

### ISSUE THREAD

**Issue by aliuk2012** [firebug/firebug.next#322]
Just saw this tweet and thought we should try implement it https://twitter.com/WickyNilliams/status/514730121912397824

**Comment by fflorent** [comment]
Actually that would be a reimplementation ;). Firebug 2.0 used to have it.

I think that is probably part of the commands that the DevTools should 
have natively.

Florent

**Comment by fflorent** [comment]
I don't think that's [reported yet](https://bugzilla.mozilla.org/buglist.cgi?list_id=11980690&short_desc=copy&resolution=---&query_format=advanced&short_desc_type=allwordssubstr&component=Developer%20Tools%3A%20Console). That could be a nice first-bug for you if you want to.

Note that the Firebug 2.0 code of it is [here](https://github.com/firebug/firebug/blob/923845aa917ead8bcd0390e98a14a694ccdce9ba/extension/content/firebug/console/commandLineAPI.js#L203-L207).

Florent

**Comment by josephmgonzalez** [comment]
Hi,

This is going to be my first bug for a student group project but I can't seem to find where the commandAPI for Firebug.next is? I've searched through all of the files but had no luck. Once I know where it is my team and I will be able to work on this.

Thanks! - Jose

**Comment by fflorent** [comment]
This is implemented platform side:
https://bugzilla.mozilla.org/show_bug.cgi?id=1005870

@josephmgonzalez : The copy command is implemented in the Firefox DevTools, so we inherit from they starting from Firefox 38 (currently it is the Developer Edition).

Florent

**Comment by janodvarko** [comment]
@josephmgonzalez: we need to find new good first bug for you..

Honza

**Comment by josephmgonzalez** [comment]
Sounds good, I will take a look around at other issues to see if I find any that I think I can tackle. Thanks!

- Jose
