### ISSUE TITLE
Import head.js files from the DevTools

### ISSUE THREAD

**Issue by fflorent** [firebug/firebug.next#324]
The DevTools have tests that we can benefit, especially for their head files.

A node module should:
* have a script to copy and modularize the head.js files (with the right imports, detect the dependencies for each of them)
* expose these scripts so they can be reused by other projects (like Firebug)

Florent

**Comment by janodvarko** [comment]
@fflorent  are you working on this?
(if not, please close)

Honza

**Comment by fflorent** [comment]
No. I close it.

Florent
