### ISSUE TITLE
Inspector tab shows no content after pagereload with open console tab

### ISSUE THREAD

**Issue by nbennke** [firebug/firebug.next#328]
Please open the Firebug and switch to the console tab.
Reload the current webpage and than switch back to the inspector tab. It only shows the breadcrumb but no site content. I found no other way to fix this except by closing the firebug window end reopening it. Thats annoying.
![firebug-empty-inspector-tab](https://cloud.githubusercontent.com/assets/126709/6163757/d8d9cec2-b296-11e4-8f79-522bd9da843f.png)

**Comment by janodvarko** [comment]
Fixed with above commit.
The patch will be part of Firebug 3 alpha 9 (available tomorrow or next week)

Thanks for the report!

Honza

**Comment by janodvarko** [comment]
$fixed firebug-3.0.0-alpha.9

http://getfirebug.com/releases/firebug/3.0/firebug-3.0.0-alpha.9.xpi

Honza
