### ISSUE TITLE
Box model highlighter like in FB 2.x

### ISSUE THREAD

**Issue by no-one** [firebug/firebug.next#331]
Hi,
I miss the "old" box model highlighter which only shows padding/border/margin in different colors. No "grid-lines", no box which shows the current element or something else. Will this view have a comeback in FB 3?

**Comment by aliuk2012** [comment]
Thanks for reporting.

So the "Box Model" tab should be named "Layout"? I agree I use this quiet a lot and I too like FB2 implementation of it. Also it should include the options to show Rules and guidelines

**Comment by no-one** [comment]
Here you can see what I mean: I like the "cleaner" look of FB v2 without the other stuff:
![Compare FB v2 with FF](http://oi58.tinypic.com/25s4rqg.jpg)
I want to see the colors for content/padding/border/margin while I inspect an element, nothing more. I hope this will be possible.

**Comment by no-one** [comment]
Since my last post, FF changed the default colors of padding/border/margin - I like it. :)
Is it now possible to disable the "grid-lines" with `FB 3 beta 1`?
