### ISSUE TITLE
Make firebug features available for all themes

### ISSUE THREAD

**Issue by nt1m** [firebug/firebug.next#335]
I personally don't like the Firebug theme, and prefer to use the built-in ones. It'd be nice if those themes could get the Firebug features.

**Comment by jomo** [comment]
:+1: I learned today that switching themes disables all Firebug features :/

**Comment by janodvarko** [comment]
Yeah, we are still discussing this and I tend to agree, Firebug features should be available in other themes too.

Honza

**Comment by PingusPepan** [comment]
I'd also love this because for me, the firebug theme is buggy on Linux and I prefer the Light theme.

**Comment by janodvarko** [comment]
New features that are part of Firebug 3 are now available in other themes too.

Honza
