### ISSUE TITLE
Several major issues with the Inspector panel

### ISSUE THREAD

**Issue by globexdesigns** [firebug/firebug.next#336]
Im having these following major issues with the Inspector panel in Firefox dev tools + Firebug 3.0 alpha 9.

- At some point (I can't yet determine what exactly causes this) the Inspector DOM tree will disappear from the panel. The breadcrumb navigation is still there, but the DOM tree itself is completely missing. Only restarting Firefox fixes the issue.
- Sometimes (seems random) when hovering over items in the DOM tree, the gray box-model overlays which appear on the page will stick/freeze and will not update after moving to another item in the DOM tree. This essentially renders the viewport of the website un-usable. Restarting Firefox, or closing that tab is the only way to get out of the problem.

I would consider these critical issues.

**Comment by ribagek** [comment]
the Inspector DOM tree will disappear from the panel

also have this, absolutely need urgent fixing

**Comment by globexdesigns** [comment]
I can now consistently reproduce the second issue. This occurs when you have a CSS rule defined for a common element (ie. `div {display: block}` or `span {font-size: 10}`). Hovering over a highly popular CSS rule in the Rides sidebar section of the Inspector panel will sometimes cause the overlays to stick to the viewport forever - requiring a refresh of the page. See screenshot below:

![firebug](https://cloud.githubusercontent.com/assets/226640/6305498/8ace7ce6-b8e0-11e4-95b3-148563062cd4.png)

**Comment by janodvarko** [comment]
> the Inspector DOM tree will disappear from the panel

This is a platform bug and it needs to be fixed in Firefox. See also: #448
The second issue is also platform bug, please report both in bugzilla

https://bugzilla.mozilla.org/

Honza
