### ISSUE TITLE
Theme keeps resetting to Firebug theme

### ISSUE THREAD

**Issue by jomo** [firebug/firebug.next#337]
I'm using the `Light theme` and every once in a while it's automatically switched to the `Firebug theme` 

The last time this happened was today, a few hours ago maybe.
I'm not really sure when this exactly happens, maybe after Firebug updates?
There was a [new release yesterday](https://github.com/firebug/firebug.next/releases/tag/firebug-3.0.0-alpha.9).

**Comment by janodvarko** [comment]
Yep, this happens on update. Perhaps we could introduce an option to disable this...?
Btw. what exactly looks odd in your browser. It should be fixed in any case.

Honza

**Comment by jomo** [comment]
Just noticed that the `Firebug theme` defaults to not `Use Developer Edition browser theme`.
When I disable that for the Light / Dark theme I have similar issues:

* the line drawn around the tab is way darker than the rest of the UI, I feel like it should either:
  * have the same color as the URL bar, or
  * should be continued between the URL and tab bar
* the back button seems to have an unclean border, but it might just be personal taste.

Enabling the developer edition theme fixes this for the firebug theme as well, but then some of the menu buttons + the URL bar are light on a light background.

I also dislike the Firebug theme because Firebug's blue-ish rounded-border theme doesn't fit the rest of the browser's theme:
![comparison screenshot](https://i.imgur.com/CJpFpYB.png)

The light theme doesn't have as many differences to the browser theme and it also has flat icons which look nicer IMO.

**Comment by jomo** [comment]
> * the line drawn around the tab is way darker than the rest of the UI, I feel like it should [..] be continued between the URL and tab bar
* the back button seems to have an unclean border, but it might just be personal taste.

My fault, this was caused by [Classic Theme Restorer](https://addons.mozilla.org/addon/classicthemerestorer/).

**Comment by janodvarko** [comment]
Alright, the Firebug theme is activated automatically only after installation (not after update and enabled)

Honza
