### ISSUE TITLE
Issue #30 not being reports as resolved in alpha release notes

### ISSUE THREAD

**Issue by aliuk2012** [firebug/firebug.next#338]
I fixed issue #30 but its not listed in the release notes. I thoughts it would have appears in alpha 8 or 9 but its not in either.

**Comment by janodvarko** [comment]
Ah, thanks, I marked the issue as fixed in alpha 8.

Honza

**Comment by aliuk2012** [comment]
I still dont see it listed as fixed in Alpha 8.

**Comment by janodvarko** [comment]
Yep, I know, I am asking here:
https://github.com/firebug/firebug.next/issues/313#issuecomment-75017806

Honza
