### ISSUE TITLE
Firefox 36.0 and Firebug 2.0.8 hangs

### ISSUE THREAD

**Issue by alonando** [firebug/firebug.next#340]
This is in a Windows 7 machine.

After the Firefox 36.0 upgrade when I reload a page that has Firebug active Firefox hangs for a while. It takes 10+ seconds for Firefox+Firebug to become responsive again.

If I turn off Firebug the page reloads just fine.

Note that the page is being served from localhost by Tomcat. Another clue is that this application uses Sencha ExtJS library. This does not seem to happen when debugging other pages from the internet.

I wish I had more information but had to go back to Firefox 35.0.1 for now to continue working.

thanks

**Comment by aliuk2012** [comment]
Thanks for this report however this repo and issue tracker is only specific to Firefox.next i.e Firefox 3 please can you report this over at https://github.com/firebug/firebug/issues
