### ISSUE TITLE
Minified CSS with long lines causes issues in Style Editor

### ISSUE THREAD

**Issue by y6nH** [firebug/firebug.next#342]
* There are no options for prettifying minified CSS, or even word-wrap in the Style Editor. This makes minified CSS difficult to work with.
* Very long lines are not processed by the syntax highlighter after 10000 characters.
* When the syntax highlighting stops before the end of a line, it is wrong on subsequent lines (it resumes where it left off, in the middle of a rule)
* When I try to add a character to the end of a very long line (73000 characters) the whole of Firefox becomes unresponsive. When I close it, an error message pops up:
![ff-crash](https://cloud.githubusercontent.com/assets/355120/6411779/ec7637ac-be73-11e4-9a4d-17a47833b599.png)

This is on Windows 7, with Firefox Developer 37.0a2 (2015-02-23).

**Comment by janodvarko** [comment]
This is a platform bug (in Firefox) and should be reported here:
http://bugzilla.mozilla.org/

Honza
