### ISSUE TITLE
NetExport autoExport doest not work

### ISSUE THREAD

**Issue by selenUser** [firebug/firebug.next#345]
FF nightly 39.0a1 (2015-02-23) + firebug-3.0.0-alpha.9.xpi

I tried like you recommend here https://groups.google.com/forum/#!topic/firebug/oJwLFniRs-E

and tried window.NetExport.triggerExport("harFile") get undefined and no file is create in the har folder

**Comment by janodvarko** [comment]
Can you please provide detailed steps describing how to reproduce the problem?
Do you have a test page I could use?

Honza

**Comment by janodvarko** [comment]
HAR export feature is now built-in Firefox, so related report needs to be reported in Bugzilla
https://bugzilla.mozilla.org/

There is also an extension that is exposing HAR API in  to the content, see:
https://github.com/firebug/har-export-trigger/
http://www.softwareishard.com/blog/har-export-trigger/

`window.NetExport.triggerExport()`  is now -> `HAR.triggerExport()`

If there is an issue with using HAR  API report it here:
https://github.com/firebug/har-export-trigger/issues

Honza
