### ISSUE TITLE
Highlight executable lines in Debugger panel

### ISSUE THREAD

**Issue by SebastianZ** [firebug/firebug.next#346]
In earlier versions of Firebug the line numbers of executable lines were displayed in green. This feature should be reintroduced.

This was initially requested in #75, which was closed earlier with the hint that this should actually be implemented in the DevTools. I created [bug 1138243](https://bugzilla.mozilla.org/show_bug.cgi?id=1138243) covering that now.
Though as Firebug 2 already had this feature, it might be worth being implemented in Firebug first.

Sebastian

**Comment by janodvarko** [comment]
This needs to be implemented on the platform.

Honza

**Comment by SebastianZ** [comment]
Panos wrote in [comment 1 of bug 1138243](https://bugzilla.mozilla.org/show_bug.cgi?id=1138243#c1), that if that feature gets implemented, it should be hidden behind a preference, which can be turned on by Firebug.

My current assumption is that it won't get implemented on the platform (if no one of the Firebug team takes the bug) and Firebug users will probably miss this feature.
So it might make sense to implement this in Firebug first (or fix the platform side).

Sebastian
