### ISSUE TITLE
Can't add styles for pseudo-selectors

### ISSUE THREAD

**Issue by jomo** [firebug/firebug.next#347]
quoting @kumarharsh from #326:

>  It is nigh-impossible to add a new style definition for pseudo-selectors. Once you right click on the CSS panel in the Inspector panel, and click on Add Rule, and then write something like body:before and press tab, poof, the thing is gone. Never to come back. The only way to do something like this is to go to the Style Editor panel.

**Comment by janodvarko** [comment]
This needs to be implement on the platform (Firefox built-in tools).
You might want to file a bug in bugzilla:
https://bugzilla.mozilla.org/enter_bug.cgi

Honza
