### ISSUE TITLE
Expand icons missing in inspector

### ISSUE THREAD

**Issue by FeyP** [firebug/firebug.next#350]
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:36.0) Gecko/20100101 Firefox/36.0
Firebug: 3.0.0-alpha.9

After upgrading from alpha.8 to alpha.9 I no longer see expand icons in the inspector tab (e.g. +/- next to the elements in Firebug 2, arrows next to the elements in alpha.8). I can still click on the blank spot next to the elements to expand them.

![fire-bug](https://cloud.githubusercontent.com/assets/1588784/6482285/92f496b6-c264-11e4-972c-cf676e4faadd.png)

**Comment by aliuk2012** [comment]
@FeyP thanks for reporting and I'll get it sorted out for you.

**Comment by FeyP** [comment]
@aliuk2012 Thank you for taking the time to work on this, it is much appreciated!
