### ISSUE TITLE
CSS completion not working

### ISSUE THREAD

**Issue by jomo** [firebug/firebug.next#355]
Consider this example:
```
element {
    position: |
}
```

I tried waiting, tab, all the arrow keys, inserting characters:
![screenshot](https://i.imgur.com/tJynuJi.gif)

---

I expected a list of suggestions: `static | relative | absolute | sticky | fixed`

**Comment by fflorent** [comment]
Sounds weird. What version of Firefox are you using ? Have you installed Firebug.next and enabled the theme ?

Because on your screencast-gif, I rather see the default light-theme.

Florent

**Comment by jomo** [comment]
FirefoxDeveloperEdition 38.0a2 (2015-03-08) & Firebug 3.0.0-alpha.9

I just tested it again it seems like it's *sometimes* working and sometimes not. This hasn't just started recently, I think it has always been like that in firebug.next.

I will try applying the latest FF update, but I guess that won't fix it.

**Comment by jomo** [comment]
> I rather see the default light-theme.

I changed it to the `Light theme` because it looks better IMO.

This was fixed itself before applying the update and now I can't reproduce it anymore. I noticed it after changing CSS on a page for a while and it also affected other sites (i.e. Google) before it fixed itself.

But as I said, this already happened several times before. Is there any way for me to debug this in case it happens again?

**Comment by fflorent** [comment]
When you go to the DevTools options, is the Firebug theme enabled ?
* If it is, despite having the light-theme like you seem in your screencast, it sounds like something is wrong with your installation (thus I would invite you to disable any other add-on, etc.)
* If it is not, could you enable it and try again ?

Thanks in advance

Florent

**Comment by fflorent** [comment]
> I changed it to the Light theme because it looks better IMO.

Well, then you don't use Firebug, but rather the "raw" DevTools ;).

> But as I said, this already happened several times before. Is there any way for me to debug this in case it happens again?

Sure : please, try Ctrl-Shift-J and look for errors. It is appreciated in bug reports :).

Florent

**Comment by fflorent** [comment]
> This was fixed itself before applying the update and now I can't reproduce it anymore. I noticed it after changing CSS on a page for a while and it also affected other sites (i.e. Google) before it fixed itself.

May I close the bug ? (and if it happens again, could you report it to the DevTools at http://bugzilla.mozilla.org ?).

Florent

**Comment by jomo** [comment]
> Well, then you don't use Firebug, but rather the "raw" DevTools ;).

Well I didn't know that, it's not clear at all from the UI that switching a Theme changes the behavior / disables Firebug:
![theme](https://i.imgur.com/Yotgowk.png)

Quote from Wikipedia:
> a theme is a preset package containing graphical appearance details
> Themes are used to customize the look and feel

----

I will report it to bugzilla.

PS: the Firebug theme is rather ugly compared to the Light theme :(

**Comment by fflorent** [comment]
> Well I didn't know that, it's not clear at all from the UI that switching a Theme changes the behavior / disables Firebug:
> Quote from Wikipedia:

That's indeed a recurrent remark. We offer both (a theme and extra-features).

> PS: the Firebug theme is rather ugly compared to the Light theme :(

We would be interested in your feedback for that question (with precise points). Note that we want to look like the good old Firebug.

Florent

**Comment by jomo** [comment]
related: #335

I gave some feedback [here](https://github.com/firebug/firebug.next/issues/337#issuecomment-74933044) in #337.

**Comment by jomo** [comment]
> could you report it to the DevTools

[Bug 1141148](https://bugzilla.mozilla.org/show_bug.cgi?id=1141148)

**Comment by fflorent** [comment]
Thanks

Florent
