### ISSUE TITLE
Enable Github oAuth app policy

### ISSUE THREAD

**Issue by cadorn** [firebug/firebug.next#357]
Please enable: https://github.com/organizations/firebug/settings/oauth_application_policy

**Comment by fflorent** [comment]
What for ?

Florent

**Comment by cadorn** [comment]
So when I give a third party app access to some of my github organizations it does not include firebug by default.

**Comment by janodvarko** [comment]
Does it work for you now?

Honza

**Comment by cadorn** [comment]
Yes.
