### ISSUE TITLE
Ajax view in console

### ISSUE THREAD

**Issue by compojoom** [firebug/firebug.next#358]
I saw that you've marked #180 as resolved, so I decided to give alpha9 a try. 

I've selected the net tab, selected Log & log request and response bodies and I really see the the ajax requests there. However I also see all net resources being loaded (such as images for example). Is there any way to just filter by XHR requests???
In the network tab I have selected only XHR, but this doesn't have any effect in the console.

Also the url of the ajax request is not displayed fully. It just shows the domain + path, but it doesn't show the query parameters. That makes it confusing when you are looking for a specific request. 
![logging](https://cloud.githubusercontent.com/assets/693770/6663221/ac8ce18c-cbc4-11e4-8ec9-9a317b2cc310.PNG)
![query](https://cloud.githubusercontent.com/assets/693770/6663222/ac8d08f6-cbc4-11e4-8027-0ada0d891610.PNG)

**Comment by janodvarko** [comment]
The Console panel has its own filter. See the attached screenshot.

![358](https://cloud.githubusercontent.com/assets/37785/6664274/8fa3e58e-cbce-11e4-967b-7b0ef8d64de4.png)

Does it work for you?

> Also the url of the ajax request is not displayed fully. It just shows the domain + path, but it doesn't
> show the query parameters. That makes it confusing when you are looking for a specific request. 

Note that there is a tooltip that shows the entire URL, but perhaps we could show the tooltip immediately on hover? (just like in Firebug 2)

Honza

**Comment by compojoom** [comment]
Hm, I don't have this. I only have errors, warnings and log. XHR is not in the list. I've installed alpha 9 from here: https://getfirebug.com/releases/firebug/3.0/ - is there anything I need to select as an option to enable this?

The tooltip doesn't solve the issue. You still have to hover over all request to find out the one you need. The old behavior in ff2 was golden. Nearly the full url was displayed, so no user interaction was needed other than scanning the urls with your eyes to find the right one.

**Comment by janodvarko** [comment]
> Hm, I don't have this. 

It isn't in the release channel yet. You might want to try DevEdition
https://www.mozilla.org/en-US/firefox/developer/

> The tooltip doesn't solve the issue. You still have to hover over all request to find out the
> one you need. The old behavior in ff2 was golden. 

I see, this would be useful. If the first problem is solved, we can rename this issue report and focus on the URL.

Honza

**Comment by compojoom** [comment]
Okay, I'll open a new issue for the URL. 
Running firebug.next on ff DEV fixed the XHR issue.

**Comment by janodvarko** [comment]
Great, thanks

Honza
