### ISSUE TITLE
Reimplement the monitorEvents() and unmonitorEvents() commands

### ISSUE THREAD

**Issue by SebastianZ** [firebug/firebug.next#363]
The command line should offer the [`monitorEvents()`](http://getfirebug.com/wiki/index.php/MonitorEvents) and [`unmonitorEvents()`](http://getfirebug.com/wiki/index.php/UnmonitorEvents) commands.

Sebastian

**Comment by janodvarko** [comment]
Just like the other missing command line API, this one should also be implemented on the platform.

Honza

**Comment by SebastianZ** [comment]
This was filed as [bug 1165138](https://bugzilla.mozilla.org/show_bug.cgi?id=1165138).

Sebastian
