### ISSUE TITLE
Reimplement the getEventListeners() command

### ISSUE THREAD

**Issue by SebastianZ** [firebug/firebug.next#364]
The command line should offer the [`getEventListeners()`](http://getfirebug.com/wiki/index.php/GetEventListeners) command.

Sebastian

**Comment by janodvarko** [comment]
This should be done on the platform (not sure if it's reported in bugzilla, but would be nice to have it there).

Honza

**Comment by SebastianZ** [comment]
Filed as [bug 1227044](https://bugzilla.mozilla.org/show_bug.cgi?id=1227044).

Sebastian

**Comment by SebastianZ** [comment]
Just realized that this was already filed as [bug 1164285](https://bugzilla.mozilla.org/show_bug.cgi?id=1164285).

Sebastian
