### ISSUE TITLE
Implement advanced options for $x() command

### ISSUE THREAD

**Issue by SebastianZ** [firebug/firebug.next#365]
The [`$x()`](http://getfirebug.com/wiki/index.php/$x) command available within the command line should offer the additional optional parameters for context node and result type as in Firebug 2.

Sebastian

**Comment by janodvarko** [comment]
This is a platform issue and if not fixed yet, it should be reported in bugzilla.

Honza

**Comment by SebastianZ** [comment]
Ok, filed as https://bugzil.la/1227040 now.

Sebastian

**Comment by SebastianZ** [comment]
Just realized that this was already filed as [bug 1164195](https://bugzilla.mozilla.org/show_bug.cgi?id=1164195).

Sebastian
