### ISSUE TITLE
Reimplement monitor() and unmonitor() commands

### ISSUE THREAD

**Issue by SebastianZ** [firebug/firebug.next#366]
The command line should offer the [`monitor()`](http://getfirebug.com/wiki/index.php/Monitor) and [`unmonitor()`](http://getfirebug.com/wiki/index.php/Unmonitor) commands.

Sebastian

**Comment by janodvarko** [comment]
This should be done on the platform
Honza

**Comment by SebastianZ** [comment]
Filed as [bug 1227042](https://bugzilla.mozilla.org/show_bug.cgi?id=1227042).

Sebastian

**Comment by SebastianZ** [comment]
Just realized that Florent already filed that earlier as [bug 1164882](https://bugzilla.mozilla.org/show_bug.cgi?id=1164882).

Sebastian
