### ISSUE TITLE
Firebug Menu is missing in non firebug theme

### ISSUE THREAD

**Issue by nbennke** [firebug/firebug.next#368]
As visible in screenshots the button for the firebug menu is only visible in the firebug theme. The other themes don't provide the button.

![missing_firebug_menu_1](https://cloud.githubusercontent.com/assets/126709/6726103/3ab387c2-ce13-11e4-8e4a-104da0127a50.png)
![missing_firebug_menu_2](https://cloud.githubusercontent.com/assets/126709/6726104/3ab52eec-ce13-11e4-9d6b-b178bd4af751.png)

**Comment by fflorent** [comment]
Well, that's intended: Firebug is activated when the theme is selected (at least, for now, it is being discussed).

Florent

**Comment by nbennke** [comment]
Firebug.next 3.0.0-alpha.9, Firefox 36.0.1

**Comment by janodvarko** [comment]
The comment above is correct, it's a feature not a bug, closing this report.

Honza
