### ISSUE TITLE
Fold / unfold elements not visible in inspector tab of firebug theme

### ISSUE THREAD

**Issue by nbennke** [firebug/firebug.next#369]
When using the firebug theme the elements zu fold or unfold objects within the inspector tab are not visible. They are there but not visible in front of the DOM elements as in the other themes. The current situation makes it hard to use the folding or unfolding in the firebug theme...

![firebug-invisible-fold-buttons](https://cloud.githubusercontent.com/assets/126709/6726301/d834ed04-ce15-11e4-9cd9-67897acc0ef0.png)
![firebug-visible-fold-buttons](https://cloud.githubusercontent.com/assets/126709/6726300/d8346ffa-ce15-11e4-824f-fa4f3a766a90.png)

**Comment by fflorent** [comment]
Thanks for the report.

I used to have this bug long ago. Can you tell us your Firebug.next + Firefox version please?

Thanks in advance,
Florent

**Comment by nbennke** [comment]
Firebug.next 3.0.0-alpha.9, Firefox 36.0.1

**Comment by nbennke** [comment]
I've now updated my Firefox via Ubuntu updates to Version 36.0.4, but the bug is still alive...

**Comment by fflorent** [comment]
Yeah, these were security updates.

Could you try using Firefox developer edition please, and give us feedback?

Florent

**Comment by fflorent** [comment]
Oh, I've just reproduced it on my work machine (using developer edition).

Florent

**Comment by fflorent** [comment]
Ahah, already fixed in 9e8ddb5 :-).

You have to wait for the next alpha release. Or is it a blocker for you?

Florent

**Comment by nbennke** [comment]
Next release is fine.
