### ISSUE TITLE
Unable to edit / remove cookies in the storage view

### ISSUE THREAD

**Issue by Gidmark** [firebug/firebug.next#373]
In the previous version this was possible and was one of the gold features imho

**Comment by fflorent** [comment]
Hello,

Thanks for the report. It is being implemented platform-side:
https://bugzilla.mozilla.org/show_bug.cgi?id=1031192

Florent

**Comment by jhdxr** [comment]
three month has past, however this issue is still new on https://bugzilla.mozilla.org/show_bug.cgi?id=1031192. 

btw, as firefox 40.0a2 introduced e10s, firebug 2.0 is not supported. is there any plan for firefox 3.0 beta?

**Comment by janodvarko** [comment]
We are working on landing Firebug 3 features and the theme directly into Firefox. It should be ready when e10s is enabled in Firefox release channel.

Honza

**Comment by janodvarko** [comment]
> is there any plan for firefox 3.0 beta?

We switched to beta already, beta 1 available: https://github.com/firebug/firebug.next/releases

It'll also be available on AMO soon.

Currently you need to flip `xpinstall.signatures.required` to false.

Honza

**Comment by ari** [comment]
Should this ticket actually be closed? The cookie editing feature is a very useful one, so perhaps it should be considered a regression to ship Firebug 3.0 without it.

Looking at the mozilla tickets, it doesn't look like any work has started on this at their end, and they haven't even been triaged into a target release milestone.

**Comment by janodvarko** [comment]
This should be fixed on the platform, so important thing is that there is proper bugzilla bug reported.
Firebug.next is mostly focused on Firebug theme for devtools.
Honza

**Comment by ari** [comment]
Ah, my misunderstanding. I hadn't realised that Firebug 3 was nothing but a theme around Mozilla's tools. I thought it extended and enhanced them.

I'll go back to firebug 2.x which has everything I need. Hopefully that platform will be supported for a long time.

**Comment by Gidmark** [comment]
Second that @ari.
In a sense the platform got support for it "cookie list" and "cookie remove ..." in the dev toolbar, but it would be sweeter to have it like in 2.x.
