### ISSUE TITLE
Console XHR requests show empty response (even with log request and..) in e10s

### ISSUE THREAD

**Issue by TheLaGmAn** [firebug/firebug.next#379]
1. Use FF Nighly to have e10s.
2. Go to www.google.com
3. Enable xor logging (this should come enabled by default)
4. write something in the google search input
5. look for the ajax call, open it, look in the response tab, its empty.

If you run the tab in non-e10s mode it works.

additional: json responses that are long (non objects, plain text) gets cropped with "..." and no way to see it completly (it was possible on firebug 2).

**Comment by TheLaGmAn** [comment]
I been digging a bit (keep in mind i have ZERO experience developing/debugging firefox addons).
What i could find so far is:

console/xhr/json-viewer.js handles the init when the XHR log is open,
[code]
  initTabBody: makeInfallible(function({netInfoBody, file}) {
    Trace.sysout("jsonviewer.initTabBody", arguments);
 file.requestData("getResponseContent").then(response => {
      file.content = response.content;
[...]
[/code]

Now in response.content we should have the content of the XHR response, but in the e10s windows, this content.TEXT has garbage characters, for ex, the google example sets the var with:

""

when in the non e10s window, the var has:

"["gdd",[["gdd\u003cb\u003er5\u003c\/b\u003e",0],["gdd\u003cb\u003er5 vs ddr3\u003c\/b\u003e",0],["gdd",0],["gdd\u003cb\u003ekia\u003c\/b\u003e",0],["gdd\u003cb\u003er3 vs gddr5\u003c\/b\u003e",0],["gdd\u003cb\u003er6\u003c\/b\u003e",0],["gdd\u003cb\u003er5 vs ddr5\u003c\/b\u003e",0],["gdd\u003cb\u003er\u003c\/b\u003e",0],["\u003cb\u003eddrescue\u003c\/b\u003e",0,[10],{"za":"\u003csc\u003eddrescue\u003c\/sc\u003e","zb":"\u003cse\u003egddrescue\u003c\/se\u003e"}],["gdd\u003cb\u003er3\u003c\/b\u003e",0]],{"j":"4n","q":"FbPfJb6tXJgxPHLb_Fx3gItdzEs"}]"


So thats the issue right there, the content.TEXT comes with corrupted data, now we have to find WHY does it throw corrupted data

**Comment by TheLaGmAn** [comment]
is anyone working on this issues?

**Comment by fflorent** [comment]
I can't reproduce that using the Nightly of the 2015-05-10. Here is a screencast: 
https://drive.google.com/file/d/0B5NqEPwxS4QwZXpyN0hmUDNDeGM/view?usp=sharing

Do I have other steps to include in the scenario?

Otherwise, have you tried [using a fresh Firefox profile](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles?redirectlocale=en-US&redirectslug=Managing+profiles) to test whether it works?

Thanks in advance,
Florent

**Comment by TheLaGmAn** [comment]
okay, updated ff to the one of 05-10, it seems to work now, seems like they fixed it, thanks for your reply!

**Comment by fflorent** [comment]
You're welcome. Thanks for the report and the feedback!

Florent
