### ISSUE TITLE
Firebug3 - not honoring 'netexport.pageLoadedTimeout' config

### ISSUE THREAD

**Issue by senthilprabhut** [firebug/firebug.next#382]
When I wanted only one har file that was generated by User trigger, I set the value of "**netexport.pageLoadedTimeout**" to 0  and used **window.NetExport.triggerExport()**  in the program.

I ran the test against *google.com* (you just need java to run the attached program), it created two files (one auto-export and one for javascript call) instead of one.
![outputlogfiles](https://cloud.githubusercontent.com/assets/4954550/7088621/ddb69b8e-dfb2-11e4-93b7-3a9f9bcd42c7.png)

To make sure I has set the correct values, I verified it in about:config (attached screenshot)
![about-config-screenshot](https://cloud.githubusercontent.com/assets/4954550/7088618/d4e8414c-dfb2-11e4-946b-f07429f58e50.png)

I was able to attach the FBTrace with the test run and saw the sequence below  -  the Exporter.buildData is called twice while we expect only one call.
>    "index": 428, "text": "HarCollector.waitForTimeout; 0"
>    "index": 429, "text": "HarCollector.waitForPageLoad; DONE Page loaded!"
>    "index": 430, "text": "exporter.buildJSON; Number of entries: 22"
>    "index": 431, "text": "Exporter.buildHAR;"
>    "index": 432, "text": "Exporter.buildData; Exported data:"    
>    "index": 433, "text": "exporter.buildJSON; Number of entries: 22"
>    "index": 434, "text": "Exporter.buildHAR;"
>    "index": 435, "text": "Exporter.buildData; Exported data:"

With "alwaysEnableAutoExport=true"  and with "pageLoadedTimeout=0", and with No javascript call, I'm still getting one log file.

**Comment by senthilprabhut** [comment]
[java test and firebug trace log hosted in onedrive](https://onedrive.live.com/redir?resid=F5D1CF7B8F438D9D!30119&authkey=!ANk6Kr-zkiK71UE&ithint=folder%2czip)

**Comment by janodvarko** [comment]
HAR export feature is now built in Firefox and there is also HARExportTrigger that exposes HAR API to the content. 

If you need just HAR.triggerExport() (former `window.NetExport.triggerExport()`) set extensions.netmonitor.har.enableAutomation to true.

See more:
http://www.softwareishard.com/blog/har-export-trigger/
https://github.com/firebug/har-export-trigger/wiki/Examples

Please report any other related issues in http://bugzilla.mozilla.org/ (HAR Export) or https://github.com/firebug/har-export-trigger/ (HAR API)

Honza
