### ISSUE TITLE
HAR isn't generated with Proxy 

### ISSUE THREAD

**Issue by JosephCastro** [firebug/firebug.next#384]
Hi.

I test this case, first with Python Selenium and didn't work, now I test this manually, in firefox, configuring a Proxy in the preferences tab and I can't get the HAR file, even if I try to do by clicking in export option.

If I no use proxy, this works without problem.

-- Edit --

How to reproduce:

- Install Firebug.Next and configuring to access API (even without this you get the same result)
- Change the proxy configuration to any proxy
- Test any page, trying to get the HAR file through export button or with the API.

**Comment by janodvarko** [comment]
I can help with this one. Can you please provide detailed instructions how to properly configure the browser?

Honza

**Comment by JosephCastro** [comment]
Please.

Instructions: 

1. I have firefox 37.0.1 , with no plugins installed, except for Firebug 3.0.0-alpha.9
2. Then I config firebug to autoExport and adding the secretToken to get the API call
3. I change the proxy configuration (Preferences -> Advanced -> Net -> Connection -> Config), then I add a proxy (for HTTP and HTTPS) you can select one of this http://proxylist.hidemyass.com/#listable 
4. Then I open any page to test and try to get the HAR file for API and manually (Export button -> Save as Har ... )

This is the firebug netexport configuration:
![captura de pantalla 2015-04-21 a las 10 27 27](https://cloud.githubusercontent.com/assets/824188/7253192/2d647ec4-e811-11e4-87d2-927ab2975f19.png)

**Comment by janodvarko** [comment]
Thanks

I tried (it was hard to find a working proxy from the list, but) and I was successful couple of times and in case the page finished loading I could see a new HAR file in the output directory and when I manually exported HAR a saw preview of it (showPreview set to true) and new HAR file in the dir I picked.

Can you try Firebug 3 alpha 11 (the latest) and also Firefox Nightly?
Does it help?

Honza

**Comment by JosephCastro** [comment]
With Firebug 3 - Alpha 11 and Firefox Nightly, I can save the HAR (manually), but I can't access to the API call ( window.NetExport.triggerExecute('<secret-token>') )  :C

**Comment by janodvarko** [comment]
Can you try a12?
http://getfirebug.com/releases/firebug/3.0/firebug-3.0.0-alpha.12.xpi

Honza

**Comment by JosephCastro** [comment]
With 12 I can save the HAR manually, but still can't access to the API, I get: 
```TypeError: window.NetExport is undefined```

**Comment by janodvarko** [comment]
Does the following STR work for you?

1. Open the toolbox go the to the Network panel and set Auto Export 
2. Reload the page 
3. Go to the Console panel and execute: NetExport.triggerExport() in the command line
4. Check out the log directory. Do you see the file?

Honza

**Comment by JosephCastro** [comment]
Nope.
The Auto Export, doesn't export and NetExport.triggerExport() give me ```ReferenceError: NetExport is not defined``` (and the previous notation window.NetExport ...  still ```TypeError: window.NetExport is undefined```

**Comment by janodvarko** [comment]
This is weird, it works for me.
Note that I am not talking about 
extensions.firebug.netexport.alwaysEnableAutoExport

You just need to manually check the option in the Options menu...

Honza

**Comment by JosephCastro** [comment]
Yep, I do it manually.
Now I install modify-headers, let me try without it.

**Comment by JosephCastro** [comment]
:C 
Nothing of nothing.
I'm using 62.201.200.5:8080 as proxy (for testing only, because I generally use a paid one), with
Firebug3-A12 (the only plugin that I have install)
FirefoxNightly 40.0a1
with the same configuration that previously send you and now I can't save manually HAR, I get the same errors with the API call, also I testing this site [http://www.iplocation.net/](http://www.iplocation.net/)

**Comment by JosephCastro** [comment]
Hi

I uninstall all firefox stuff and clean/remove all config files.
Then install Firefox Nightly 40 + Firebug 3 - Alpha -12, with no configuration in firebug, also without using a proxy. I load any page and then I tried to save the HAR manually, but nothing happen, the HAR file doesn't save.

**Comment by janodvarko** [comment]
@JosephCastro is this still a problem?

If yes, please create a new report here:
https://github.com/firebug/har-export-trigger/issues

Honza
