### ISSUE TITLE
Open post ajax request in a new tab?

### ISSUE THREAD

**Issue by compojoom** [firebug/firebug.next#388]
With FB 2 it was possible to open a post ajax request in a new tab. When we are in the new tab -> the request was sent through POST with the same parameters. IN FB3 we are sending a get request I think. With FB2 I was able to send 100 ajax request till one of them broke. I was able to open this one in a new tab and debug from there. Right now that's no longer possible.

**Comment by compojoom** [comment]
Any progress on this? Is this a firebug issue or firefox's console issue? Should I create a topic with the firefox team?

**Comment by SBhojani** [comment]
Seems to occur only when the POST body is empty.

**Comment by compojoom** [comment]
Really? For me that is always the case. No matter if the post body is empty or not.

**Comment by janodvarko** [comment]
This is Firebug issue and I'll do some analyses

(but it can take some time since I am planning vacation)

Honza

**Comment by sebastienbarre** [comment]
Afraid to report the same. I'm using Firefox 51 (beta) and I switched to the Firefox Developer Tools, thinking that Firebug had been integrated. "Open in new Tab" on a POST request will result in a GET request in the new tab. That's unfortunate, that was a useful debugging feature...

**Comment by SebastianZ** [comment]
This is reported to the DevTools in [bug 1220758](https://bugzilla.mozilla.org/show_bug.cgi?id=1220758).

Sebastian
