### ISSUE TITLE
Events cant be disabled

### ISSUE THREAD

**Issue by TheLaGmAn** [firebug/firebug.next#394]
One feature missing in the new system is the ability to DISABLE an event, with the new setup in the HTML mockup you can not disable an event.

Secondly, the old way of having a separate TAB for the Events was a lot better for a lot of users, please add support to add it back.

**Comment by TheLaGmAn** [comment]
is there any info on this? can be done as it was before so we can disable events? and also add an option so we can have the old tab on the right panel with the events?

**Comment by fflorent** [comment]
Yes, that was a nice feature. My guess is that it's worth to implement it in the native devtools.

Florent

**Comment by janodvarko** [comment]
> Yes, that was a nice feature. My guess is that it's worth to implement it in the native devtools.

Agreed

@fflorent why the beta label? Shouldn't we just close issues that belongs to the platform and point the reporter to bugzilla issue list?


Honza

**Comment by janodvarko** [comment]
Closing this (this is platform issue)

Honza

**Comment by fflorent** [comment]
@janodvarko I don't know... Anyway, that should be reported in bugzilla:
https://bugzilla.mozilla.org

@TheLaGmAn Would you mind to report it? Or should I do?

Florent

**Comment by TheLaGmAn** [comment]
@fflorent , if you can, report it yourself, i have never used bugzilla before and i would probably end up adding it in the wrong place.
Thanks a lot!

**Comment by fflorent** [comment]
Reported [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1226637) and [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1226640). Don't hesitate to reply and CC yourself to get news.

Florent

**Comment by TheLaGmAn** [comment]
Thanks, will do!
