### ISSUE TITLE
XHR JSON Response is stripped and missing feature

### ISSUE THREAD

**Issue by TheLaGmAn** [firebug/firebug.next#395]
When looking at JSON XHR response in the JSON tab of the XHR, the response of each element is shortened with "..." in the middle of the content and there is no way to see the full response in the XHR call as JSON, in FB2 there was a + button to show it completly, now this is missing

**Comment by TheLaGmAn** [comment]
This has been sort of fixed.
Now it does show the + to show the content but when it does, at the bottom, it splits every character of the response in an array.
for ex, if the response is for a variable "res" : "abcdef" it will show

---------------------------------------------
[+] res: "ab..ef"
---------------------------------------------

 when expanding it shows

---------------------------------------------
[-] res: "abcdef"
0: "a"
1: "b"
2: "c"
3: "d"
4: "e"
5: "f"
---------------------------------------------

so all the 0 to 5 should be removed, imagine responses that contain plain text, how many of those will show slowing down the browser, plus making impossible to scroll down to see the next response.

**Comment by fflorent** [comment]
May be fixed with https://github.com/firebug/firebug.sdk/pull/15 (as soon as a new version of the SDK is released).

Florent

**Comment by janodvarko** [comment]
> May be fixed with firebug/firebug.sdk#15 (as soon as a new version of the SDK is released).

Firebug 3 beta 1 is already using the latest SDK, but it looks like string expansion is not yet fully fixed. I've committed another patch, hope it helps.
https://github.com/firebug/firebug.sdk/commit/36a539cbebd63619f34559c465e817e760154070

Thanks for the report

It would be great if someone can verify yet before beta 2 is released.
Honza
