### ISSUE TITLE
[Feature request] Add «Copy …» in context menu

### ISSUE THREAD

**Issue by inoyakaigor** [firebug/firebug.next#396]
![default](https://cloud.githubusercontent.com/assets/1235286/7882192/c76e05a6-0613-11e5-9b61-ca56d7c2e6d8.png)
It was very convenient for quick CSS bugfix

**Comment by cautionbug** [comment]
Even worse, when part of HTML has been converted to a text-entry, the context menu is completely inappropriate to the actual context.
![2015-06-08_1914](https://cloud.githubusercontent.com/assets/1391849/8047398/d6e13a42-0e12-11e5-8780-d79f1e8e1124.png)

**Comment by nt1m** [comment]
@inoyakaigor This will soon land on Firefox's side (which means Firebug will have it as well) : https://bugzilla.mozilla.org/show_bug.cgi?id=1024693
@cautionbug There's a WIP patch here : https://bugzilla.mozilla.org/show_bug.cgi?id=994555

**Comment by fflorent** [comment]
The patch mentioned above is shipped in Firefox. 
@inoyakaigor I close the issue if you're happy with the implementation.

Florent
