### ISSUE TITLE
Can not resize DOM Side panel  

### ISSUE THREAD

**Issue by thomasandersen** [firebug/firebug.next#40]
The DOM side panel is collapsed and it is not possible to resize it using the mouse.

![screen shot 2014-07-16 at 22 07 56](https://cloud.githubusercontent.com/assets/194093/3604883/21ec226c-0d25-11e4-9794-fbe51df2d715.png)

**Comment by aliuk2012** [comment]
Just had a look at this and I'm not sure what exactly is the issue with this one. the DOM panel doesn't appear to have a side panel (while not at least on the mac OS).

Should this issue maybe be closed?

**Comment by fflorent** [comment]
@thomasandersen could you provide a scenario for this one, please?

Florent

**Comment by janodvarko** [comment]
Yep, this is a bug, the side panel splitter shouldn't be visible if there are no side panels.

STR:
1. Load google.com (not a system page see issue #98)
2. Select the DOM panel
3. The side panel splitter is visible, but it shouldn't -> BUG

You can take a look how e.g. the Console panel does it.

Honza

**Comment by janodvarko** [comment]
The resizing & splitter issues have been fixed already, but there was another padding on the right side (looking like a splitter) fixed by the patch above.

Honza
