### ISSUE TITLE
Additional Side Panel bug

### ISSUE THREAD

**Issue by aliuk2012** [firebug/firebug.next#401]
How to replicate:

1. Go to any website
2. With the "Console" (or any tab that has an "expand" sidebar button) tab open, expand the Command Editor
3. Then click the "Dock to Side of browser window" button
4. An additional sidebar gets created but Firebug console does not move to it
5. If you repeat this enough times the browsers layout starts expanding sideways

<img width="1091" alt="screen shot 2015-07-08 at 11 32 48" src="https://cloud.githubusercontent.com/assets/3441519/8568398/3415368c-2565-11e5-8d67-61b9ff8b3210.png">
<img width="1091" alt="screen shot 2015-07-08 at 11 32 56" src="https://cloud.githubusercontent.com/assets/3441519/8568395/3413d21a-2565-11e5-9934-638ea25b0197.png">
<img width="1091" alt="screen shot 2015-07-08 at 11 33 03" src="https://cloud.githubusercontent.com/assets/3441519/8568396/3413ed68-2565-11e5-941c-ac0cbe8f8c9a.png">
<img width="1091" alt="screen shot 2015-07-08 at 11 33 13" src="https://cloud.githubusercontent.com/assets/3441519/8568399/3419321e-2565-11e5-9fef-3e80fa3e9f3b.png">

I've tried this in both XP SP3 FF 39 & Mac OS FF39/Nightly with exactly the same results. Additionally if you attempt to change the position using the option from the Start button it does the same thing and will not select the right side.

**Comment by cdcmicro** [comment]
The same is true if FB is detached in its own window and attempt to dock it to the main browser window on Win7 x64 / FF 41.0.2.

It seems to reserve the pane in the target browser window, but never moves there.

**Comment by janodvarko** [comment]
Should be fixed by the patch above.

@aliuk2012 can you please verify?

Thanks for the report
Honza

**Comment by darkred** [comment]
Sorry, but how can one try the new Firebug version(build) with that patch included?
The only way is via `jpm xpi` ?
Or there is Firebug nightly? ([like it's with Greasemonkey](https://arantius.com/misc/gm-nightly/))

**Comment by janodvarko** [comment]
> The only way is via jpm xpi ?

Yes, this is the right way (we don't have nightly builds)

Honza

**Comment by darkred** [comment]
Thank you for replying.

**Comment by darkred** [comment]
So, I followed the instructions (I omitted quoting the `cd` commands)

```
git clone https://github.com/mozilla/jpm
npm install   
npm link
git clone https://github.com/firebug/firebug.next
npm install
npm link
jpm xpi
```

 and `jpm xp` generated an 670 KB `firebug@software.joehewitt.com-3.0.0-beta.1.xpi` 
but installing it in a clean profile of either FF45 Nightly or 41 stable and it does nothing: 
no toolbar button, nothing extra in devtools: it's only an entry about:addons.

**Comment by janodvarko** [comment]
Can you share your xpi, so I can try it on my machine?

Honza

**Comment by darkred** [comment]
Yes, of course: https://www.dropbox.com/s/vmm19chwlcnxf4r/firebug%40software.joehewitt.com-3.0.0-beta.1.xpi?dl=0

**Comment by janodvarko** [comment]
External modules are missing in the XPI, you need to do: npm install in firebug.next directory and generate the xpi again.

Honza

**Comment by darkred** [comment]
I'm (almost) sure I had done this initially (without getting any errors).

Anyway, here is what I got now:

```
$ npm install
npm WARN package.json firebug@3.0.0-beta.1 license should be a valid SPDX license expression
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7

npm ERR! version not found: addon-httpd@0.0.1
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Kostas\Desktop\New folder\firebug.next\npm-debug.log

```
Here is the npm-debug.log: https://www.dropbox.com/s/nzrzbecxo80vz8l/npm-debug.log?dl=0


_(I have even cloned, installed and linked `addon-sdk`)_

**Comment by janodvarko** [comment]
Looks like the license needs to be updated.
If you go to package.son (root dir) and change the licence field to: BSD-3-Clause
... does it help?

Honza

**Comment by darkred** [comment]
The `npm WARN` entry doesn't show up anymore, but the rest errors are the same:


```
$ npm install
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7

npm ERR! version not found: addon-httpd@0.0.1
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Kostas\Desktop\New folder\firebug.next\npm-debug.log
```

**Comment by janodvarko** [comment]
I've fixed the problem.
(the license is also fixed)

Please update from firebug.next repo, try again and let me know :-)

Honza

**Comment by darkred** [comment]
Yes, now it's build ok, and I confirm that the 'additional Side Panel' bug is fixed. Thanks.
Just one thing, please: does it matter (in building the xpi) 
if I upgrade node.js to 5.0.0 (from 4.2.1), i.e. upgrade npm 3.3.6 (from 2.14.7)?
Or, should I stay in 4.2.1?

**Comment by janodvarko** [comment]
> Yes, now it's build ok, and I confirm that the 'additional Side Panel' bug is fixed. Thanks.

lol, thanks for the verification!

> Just one thing, please: does it matter (in building the xpi)
> if I upgrade node.js to 5.0.0 (from 4.2.1), i.e. upgrade npm 3.3.6 (from 2.14.7)?
> Or, should I stay in 4.2.1?

I think you can upgrade, it should work (but I didn't test it)
If not, please file a new issue and I'll fix it :-)

Honza

**Comment by darkred** [comment]
Alright. I just upgraded and was built ok. Thanks again

**Comment by janodvarko** [comment]
Excellent, thanks for the update.
