### ISSUE TITLE
Theme screws the look on the latest FF dev. edition

### ISSUE THREAD

**Issue by compojoom** [firebug/firebug.next#402]
![active-tab](https://cloud.githubusercontent.com/assets/693770/8893510/38ad3052-339b-11e5-8dd8-47b056489baa.PNG)

I'm running firebug alpha 12. Since the last FF dev. edition from the 25th of July the theme is broken. It's really hard to find the currently active tab. 

As I've said in the past I think that it would be really awesome if the firebug theme was actually only applied to the dev. tools and not to the whole browser theme.

**Comment by janodvarko** [comment]
> As I've said in the past I think that it would be really awesome if the firebug theme was actually only applied to the dev. tools and not to the whole browser theme.

Yes, you are right, done.

Will be in Firebug 3 beta 11

Honza

**Comment by compojoom** [comment]
beta 11????????????????????????????
I'm still running alpha 12, when did we get to beta 11?

**Comment by janodvarko** [comment]
Oops, I wanted to type alpha 13 ;-)

Honza

**Comment by SeanKendle** [comment]
When will alpha 13 be available?   I’m not familiar with how to use GitHub
and all the other steps necessary to compile the code and create my own
.xpi file, and my boss certainly doesn’t want to pay me to learn it, ha!





Thanks,



Sean Kendle

Joyce, Inc.

Internet Solutions

412-894-8783

joyceinc.com





*From:* Jan Odvarko [mailto:notifications@github.com]
*Sent:* Thursday, August 06, 2015 9:10 AM
*To:* firebug/firebug.next <firebug.next@noreply.github.com>
*Subject:* Re: [firebug.next] Theme screws the look on the latest FF dev.
edition (#402)



Oops, I wanted to type alpha 13 ;-)

Honza

—
Reply to this email directly or view it on GitHub
<https://github.com/firebug/firebug.next/issues/402#issuecomment-128357974>.

**Comment by janodvarko** [comment]
I'll release it tomorrow.

Honza
