### ISSUE TITLE
DOM tab starts from "Document" instead of "Window"

### ISSUE THREAD

**Issue by darkphoenixff4** [firebug/firebug.next#407]
Anybody else notice this?  The DOM tab, which shows all of the objects loaded by Javascript, seems to start on the document object in Firebug.next, whereas it started from the window object in Firebug 2.0.  Starting from the window object is more useful because it's the "global" object in the browser, allowing you to view all currently defined global objects.  If you really need document, window has a reference to it already; but the reverse case is not true.

**Comment by janodvarko** [comment]
Thanks for the report, fixed!

Honza
