### ISSUE TITLE
unable to install firebug3

### ISSUE THREAD

**Issue by Flower7C3** [firebug/firebug.next#408]
I am unable to install https://getfirebug.com/releases/firebug/3.0/firebug-3.0.0-alpha.13.xpi beacuse XPI is not signed. See more info https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct#firefox:mac:fx41&mobile::m40

**Comment by janodvarko** [comment]
See issue #403 

Honza
