### ISSUE TITLE
How to use NetExport.trigger

### ISSUE THREAD

**Issue by raicabogdan** [firebug/firebug.next#410]
Hello,

Sorry for being a pain but I really spent a whole night to only test and learn this. I normally don't ask without at least trying.

I'm using firefox 40.0.3 by default (my normal browser), I installed firebug-next, last one alpha 13.

I tried using the netexport trigger to generate a har file, but it seems this does not work at all.

No error also.

My settings: 
![config](https://cloud.githubusercontent.com/assets/4399340/9875300/8edf5ce2-5bb5-11e5-9ba4-d39a3b96cb47.png)

It would be super cool if the extension could be documented. If I can help with anything, I would be more than willing to help out. But everything I've read in the past hours was something like this:

firebug 2 + netexport can do har export to file or to server. It can also do automatically to file or server. All good. But I don't know if you can use a trigger for netexport with firebug 2 at the moment, I found some old discussion where apparently was implemented, but I could not find any docs related to it. Was also receiving some errors that the reference netexport was not defined, or something similar.

Firebug 3 or firebug-next should have the netexport already in the extension. So to my understanding, the trigger should have been working at this point based on an issue here in git. However, this time I have received no errors, but was not generating it either.

So my questions are ...
1. How do you actually use this?
2. How can I help ?

Thank you again.

**Comment by janodvarko** [comment]
Take a look at this page:
http://www.softwareishard.com/blog/har-export-trigger/

This is now the supported way how to automatically export HAR (note that min Fx version is 42+)

Honza

**Comment by raicabogdan** [comment]
So then the netexport API trigger was removed ?

**Comment by janodvarko** [comment]
Yes

**Comment by raicabogdan** [comment]
I currently use Firefox 42.0a2, installed har-export-trigger, last release, 0.5.0-beta.5.

The following test page gives in error log:

ReferenceError: HAR is not defined

Am I doing anything wrong?

**Comment by janodvarko** [comment]
It should be working.

Please take a look at:
https://github.com/firebug/har-export-trigger/issues/2

Also, can you please report an issue in HARExportTrigger issue list?
(we can continue discussion there)

I'll close this one since HARExportTrigger has nothing to do with Firebug.next

Thanks!
Honza
