### ISSUE TITLE
Use fluxify for XHR viewer

### ISSUE THREAD

**Issue by janodvarko** [firebug/firebug.next#411]
User proper architecture for XHR viewer (in the Console panel)

https://github.com/mozilla/gecko-dev/tree/fx-team/browser/devtools/shared/fluxify
https://github.com/mozilla/gecko-dev/tree/fx-team/browser/devtools/debugger/content

Honza

**Comment by jsantell** [comment]
We are replacing fluxify with redux, so we have good documentation, don't have to maintain our own "fork" of it, and everything that fluxify was doing is possible with vanilla redux -- this should land today or so: https://bugzilla.mozilla.org/show_bug.cgi?id=1204173

let me know if you have any questions and I can help with porting, shouldn't be that bad, mostly just method name changes and using a reducer to replicate the emitter being passed into other reducers

**Comment by janodvarko** [comment]
This is great news, I actually wanted to rather use Redux!
As soon as I make more progress on this, I'd love to have a discussion about whether I am going in the right direction, to make sure we are on the same page. 

I want to port this feature to devtools eventually.

Honza

**Comment by janodvarko** [comment]
New issue reported: #412 

Honza
