### ISSUE TITLE
Scrollbar too narrow in dark theme

### ISSUE THREAD

**Issue by ced64k** [firebug/firebug.next#414]
When using the dark theme, the scrollbar is really narrow and difficult to catch with the mouse. In Firebug or light theme it's wider. Tested in alpha 14 on Mac OS 10.9.5.

![scrollbar](https://cloud.githubusercontent.com/assets/3351314/10451204/0630ed84-719f-11e5-93a8-35c9912f4105.png)

**Comment by fflorent** [comment]
Hi @ced64k,

If you use the Dark theme, that is not a Firebug issue but rather a Firefox DevTools one. The Firebug.next extension is only activated when the Firebug theme is on.

You may report your issue to [bugzilla](https://bugzilla.mozilla.org).

Florent

**Comment by ced64k** [comment]
Ah ok, thanks for the information.

**Comment by janodvarko** [comment]
Florent is right, closing this report.

Honza
