### ISSUE TITLE
Cannot use Firebug.next on Firefox 44.0 (nightly)

### ISSUE THREAD

**Issue by jljouannic** [firebug/firebug.next#415]
At first I was unable to install it. But following this [comment](https://github.com/firebug/firebug.next/issues/403#issuecomment-143408867) on issue #403, I managed to disable signature verification and eventually installed Firebug.next.

Now the problem is, I do not seem to be able to run Firebug. The Firebug beetle is not where is used to be and when I press F12, it launches Firefox Developer Tools. No reference either in the `Tools` > `Web Developer` sub-menu.

Still, I can see it in the `about:addons` page.

**Comment by janodvarko** [comment]
Are you running the extension from the source or using the latest release (Firebug 3 alpha 14)?

Honza

**Comment by jljouannic** [comment]
Firebug 3 alpha 14

**Comment by janodvarko** [comment]
Can you try this test build?
www.janodvarko.cz/temp/firebug.next/firebug-3.0.0-alpha.14.415.xpi
(it's from the latest source)

Honza

**Comment by jljouannic** [comment]
This one works. Thank you!

**Comment by janodvarko** [comment]
Great thanks for the feedback!
So, this issue will be fixed in the next alpha

Honza
