### ISSUE TITLE
Selection of CSS source not visible

### ISSUE THREAD

**Issue by SebastianZ** [firebug/firebug.next#416]
The selected CSS source within the *Style Editor* has the same background as the unselected items and the name is white, so it's unreadable.

![White Style Editor sources text](https://cloud.githubusercontent.com/assets/958943/10817864/35da6056-7e3d-11e5-9736-46bfe29ec338.png)

Sebastian

**Comment by SebastianZ** [comment]
Hmm, it could have been solved by using `HIghlight` as background color instead of having a fix value, though at least I can see the text now. Please also note #430.

Sebastian

**Comment by janodvarko** [comment]
> Hmm, it could have been solved by using `HIghlight` as background color instead of having a fix value, 

Not sure what you mean, can you do PR?

Honza
