### ISSUE TITLE
Media Rules panel is empty

### ISSUE THREAD

**Issue by SebastianZ** [firebug/firebug.next#417]
The *Media Rules* side panel is empty. Also, when you switch to another theme there are now two media rules side panels.

So I assume the *Media Rules* panel can be removed in favor of styling the *@media rules* panel appropriately.

Sebastian

**Comment by janodvarko** [comment]
Should not be empty anymore (if media rules are presented for the selected styles-heet)

Honza

**Comment by SebastianZ** [comment]
They are displayed now, though right after switching to the Firebug theme the panel is still empty. Should I open a new bug for that?

Sebastian

**Comment by janodvarko** [comment]
How about now?

Honza

**Comment by SebastianZ** [comment]
Yes, now it works. Thanks!

Sebastian
