### ISSUE TITLE
Button for starting to record performance is not visible enough

### ISSUE THREAD

**Issue by SebastianZ** [firebug/firebug.next#419]
The button *Start Recording Performance* within the *Performance* panel should be displayed like a button or at least be made more visible.

![*Start Recording Performance* button doesn't look like a button](https://cloud.githubusercontent.com/assets/958943/10818073/e80b0c7a-7e3e-11e5-9a3d-a1fff305ff1d.png)

Sebastian

**Comment by SebastianZ** [comment]
It looks better now, thanks!

Sebastian

**Comment by SebastianZ** [comment]
This problem reappeared now.

Sebastian

**Comment by janodvarko** [comment]
Fixed by https://github.com/firebug/firebug.next/commit/f5c642fc4fce33ef2046b22eb680b5746914cecd

**Comment by SebastianZ** [comment]
I can confirm that it's fixed again.

Sebastian
