### ISSUE TITLE
Filter button in Performance panel looks like it's deactivated

### ISSUE THREAD

**Issue by SebastianZ** [firebug/firebug.next#420]
Because the button for adjusting the filter within the *Performance* panel is gray, it looks like it's deactivated.
Therefore it should get another color.

![Filter button in *Performance* panel](https://cloud.githubusercontent.com/assets/958943/10818164/9a8f02d4-7e3f-11e5-888c-08971261d522.png)

Sebastian

**Comment by janodvarko** [comment]
Fixed, thanks for the report!

Honza

**Comment by SebastianZ** [comment]
Looks much better now. Thank you for the fast fix!

Sebastian

**Comment by SebastianZ** [comment]
It's looking deactivated again. Did the patch get reverted?

Sebastian

**Comment by janodvarko** [comment]
The stylesheet has been accidentally removed.
Should be fixed now.
https://github.com/firebug/firebug.next/commit/f5c642fc4fce33ef2046b22eb680b5746914cecd

Honza
