### ISSUE TITLE
Animation play state buttons are displayed incorrectly

### ISSUE THREAD

**Issue by SebastianZ** [firebug/firebug.next#423]
The buttons within the *Animations* side panel are displayed incorrectly.

![*Animations* side panel buttons not displayed correctly](https://cloud.githubusercontent.com/assets/958943/10818355/3edad74a-7e41-11e5-875e-b890b97eec4d.png)

Sebastian

**Comment by janodvarko** [comment]
Fixed, thanks for the report.

Honza

**Comment by SebastianZ** [comment]
Looks good now. Thank you for the fast fix!

Sebastian
