### ISSUE TITLE
Firebug breaks Network side panel tabs in other themes

### ISSUE THREAD

**Issue by SebastianZ** [firebug/firebug.next#425]
When switching to the dark or light theme while Firebug is installed, the side panel tabs within the *Network* panel are merged into a drop-down menu button at the right side.

![*Network* side panel tabs broken](https://cloud.githubusercontent.com/assets/958943/10818605/493bc332-7e43-11e5-819b-ae00861e07e3.png)

Sebastian

**Comment by janodvarko** [comment]
Thanks for the report, the patch above should fix that, please verify.

Honza

**Comment by SebastianZ** [comment]
After setting up the Firebug.next development environment again following the [steps described in the README.md](https://github.com/firebug/firebug.next/#hacking-on-firebugnext-aka-firebug-3) I see the following error within the Browser Console when I run it via `jpm run -b <path to my Nightly> -p <path to my profile>`:

> fileName:"resource://firebug-at-software-dot-joehewitt-dot-com/lib/index.js"
> lineNumber:9
> message:"Module `firebug.sdk/lib/core/trace.js` is not found at resource://gre/modules/commonjs/firebug.sdk/lib/core/trace.js"

How can I fix that error?

Sebastian

**Comment by janodvarko** [comment]
Install required modules using: npm install
(see updated readme again)

Honza

**Comment by SebastianZ** [comment]
When I do that within the Firebug.next directory I get:

> Error: version not found: 0.0.1 : addon-httpd/0.0.1

Sebastian

**Comment by SebastianZ** [comment]
Ok, when changing the version of addon-httpd to 0.1.4 it's working.

Sebastian

**Comment by lscbll0** [comment]
#425

**Comment by SebastianZ** [comment]
The tabs are working now in other themes, though in the Firebug theme it is now too high.

![Request list header too high](https://cloud.githubusercontent.com/assets/958943/10934291/38261854-82df-11e5-92d6-e5eeffd370b0.png)

Sebastian

**Comment by janodvarko** [comment]
Fixed by https://github.com/firebug/firebug.next/commit/3be5a781a8e39e7f8816e38cefc9ef9eabd6ac2e

**Comment by SebastianZ** [comment]
Works now. Thanks!

Sebastian
