### ISSUE TITLE
Firebug breaks Animations side panel in other themes

### ISSUE THREAD

**Issue by SebastianZ** [firebug/firebug.next#426]
The *Animations* side panel display is broken when you switch to the dark or light theme.

![*Animations* side panel broken](https://cloud.githubusercontent.com/assets/958943/10818678/caf614f4-7e43-11e5-8107-f02ef19968f9.png)

Sebastian

**Comment by janodvarko** [comment]
I can't reproduce this, I think it's fixed by 
https://github.com/firebug/firebug.next/commit/d7327505c5d81da41312b43d743ee9881c1af0db

Honza

**Comment by janodvarko** [comment]
Closing, feel free to reopen.

Honza

**Comment by SebastianZ** [comment]
Yes, it's ok now.

Sebastian
