### ISSUE TITLE
The Browser Console's 'Filter output' textbot is not visible when the Firebug theme is enabled.

### ISSUE THREAD

**Issue by darkred** [firebug/firebug.next#427]
Using Firebug 3.0.0 beta 1 in Nightly x64 2015-10-30.

Screenshot: 
![Imgur](http://i.imgur.com/9hkq1I4.jpg)
and one with the Firebug theme disabled:
![Imgur](http://i.imgur.com/TwLNsI1.jpg)

**Comment by janodvarko** [comment]
Fixed, thanks for the report!
Honza
