### ISSUE TITLE
Use selection text color for rules count and save link of selected CSS source items

### ISSUE THREAD

**Issue by SebastianZ** [firebug/firebug.next#430]
The whole text of selected items within the CSS sources should be shown in contrast to the background, i.e. it should not be black but white.

![Text in selected css sources using wrong color](https://cloud.githubusercontent.com/assets/958943/10934537/bcb371c4-82e0-11e5-96fa-3508152ca9cd.png)

This might be done by using `HighlightText` as text color.

Sebastian

**Comment by janodvarko** [comment]
Fixed,  using CSS vars, so maybe fixing the comment in #416

**Comment by SebastianZ** [comment]
Regarding [my comment on issue #416](https://github.com/firebug/firebug.next/issues/416#issuecomment-153662952) I meant, you could also have used the color keywords `Highlight` and `HighlightText` instead.

But using the related DevTools CSS variables is the right way to go.

Sebastian
