### ISSUE TITLE
Switching to or from the Firebug theme breaks the Performance panel display

### ISSUE THREAD

**Issue by SebastianZ** [firebug/firebug.next#431]
When there is a recording selected within the *Performance* panel and you switch to or from the Firebug theme, you'll get the following display instead of the recording result:

![Message in performance panel after switching themes](https://cloud.githubusercontent.com/assets/958943/10935036/a717795c-82e3-11e5-9978-2230a00ae0df.png)

Something similar happens when you switch the themes while the recording is running.

Sebastian

**Comment by janodvarko** [comment]
I don't see it, what exactly should I do?
Honza

**Comment by SebastianZ** [comment]
Can't reproduce it anymore. So I close this issue. If it happens again, I'll provide detailed STR.

Sebastian
