### ISSUE TITLE
Hide second filter field in Console panel

### ISSUE THREAD

**Issue by SebastianZ** [firebug/firebug.next#433]
The *Filter output* field from the DevTools within the *Console* panel should be hidden when the Firebug theme is enabled.

![Second filter field in *Console* panel](https://cloud.githubusercontent.com/assets/958943/10936023/310e6a02-82ea-11e5-95fc-122d1865e499.png)

Sebastian

**Comment by fflorent** [comment]
I take that little one.

Florent

**Comment by fflorent** [comment]
@janodvarko I just removed a rule. I am not sure about the reason of this comment:
> /* But, make the field visible in the Browser console */

Even in the Browser console, it would be redundant, right?

Florent

**Comment by fflorent** [comment]
BTW, thanks for the report Sebastian ;)

**Comment by janodvarko** [comment]
> I just removed a rule. I am not sure about the reason of this comment:

The rule must be there, but fixed.

The filter should be visible in the Browser Console (since there is no tab bar with the shared input field) and hidden is standard Console panel (since the Toolbox has the shared input field if Firebug theme is active).

Honza

**Comment by fflorent** [comment]
Ah, right, I get now what is the Browser Console.

I don't see any way to differentiate it from the "regular" Console panel in the DevTools. I report an issue and submit some patch.

Florent

**Comment by fflorent** [comment]
Reported here. I'll take a look later:
https://bugzilla.mozilla.org/show_bug.cgi?id=1221770

Florent

**Comment by janodvarko** [comment]
@fflorent I made a comment in that report.

Honza

**Comment by janodvarko** [comment]
@fflorent I forgot to ask about this on today's meeting...

 Any progress, should I help?

Honza

**Comment by fflorent** [comment]
I'll work on this today

Florent

**Comment by fflorent** [comment]
I changed the code to follow your suggestion.

I slightly adapted it : I supposed it would be more interesting to have the `panel` attribute global to each toolbox panels, so it would be reusable. What do you think?

Florent

**Comment by janodvarko** [comment]
OK, works for me, you can merge into the master, thanks!
Honza

**Comment by janodvarko** [comment]
@fflorent: I think you can close the platform bug,

Honza

**Comment by fflorent** [comment]
Yep !

**Comment by SebastianZ** [comment]
LGTM. Thank you, Florent!

Sebastian

**Comment by fflorent** [comment]
Thanks for the feedback Sebastian!

Florent
