### ISSUE TITLE
Move filter field in the Network panel to the top

### ISSUE THREAD

**Issue by SebastianZ** [firebug/firebug.next#434]
The field to filter the request URLs within the *Network* panel should be moved to the main toolbar where it's placed for the other panels.

![Move *Filter URLs* field to the top](https://cloud.githubusercontent.com/assets/958943/10936123/d21aa3a2-82ea-11e5-99fe-98e36ac1c5c0.png)

Sebastian

**Comment by fflorent** [comment]
@janodvarko PR #440 submitted :)

Florent

**Comment by fflorent** [comment]
@SebastianZ FWI, the PR has been merged :). Thanks for the report!

Florent

**Comment by SebastianZ** [comment]
Hmm, now the filter field is completely gone for me. :-(

Sebastian

**Comment by fflorent** [comment]
Yes, due to #441. That's not related to this fix.

Florent

**Comment by janodvarko** [comment]
Works for me, closing.

Thanks!
Honza
