### ISSUE TITLE
The DOM panel is not refreshed automatically

### ISSUE THREAD

**Issue by fflorent** [firebug/firebug.next#435]
STR:
1. Go to [google.com](google.com)
2. Open the DOM panel
3. Go to [duckduckgo.com](duckduckgo.com)

Expected result:
The DOM panel should be updated automatically to reflect the view of the global variables of the current page.

Actual result:
It still displays the global variables of the previous page.

Florent

**Comment by janodvarko** [comment]
Should be fixed

Does it work for you now?

Honza

**Comment by fflorent** [comment]
Yes, thanks @janodvarko 

Florent
