### ISSUE TITLE
Inspector: Missing search completion and automatic search on key press

### ISSUE THREAD

**Issue by fflorent** [firebug/firebug.next#438]
Two native features are missing in the search box of the inspector panel:
 * the completion of the CSS selector
 * the automatic search on key press event

STR:
1. Go to http://mozilla.org
2. Open the inspector panel
3. In the search box, type "#strin"
   => no completion appears
4. Type : "#strings"
   => The match is not made automatically unless the user presses enter

Florent

**Comment by fflorent** [comment]
@janodvarko Patch above. Could you please review.

Also I wonder why the `"type": "search"` attribute has been commented ? 

Florent

**Comment by janodvarko** [comment]
> Also I wonder why the "type": "search" attribute has been commented ? 

I don't remember, but your changes seem to be correct.

> The match is not made automatically unless the user presses enter

I don't understand this comment, this doesn't happens even if Firebug theme is *not* activated

Otherwise it works for me, you can merge!

Honza

**Comment by fflorent** [comment]
> I don't understand this comment, this doesn't happens even if Firebug theme is not activated

I do see that feature (automatic completion as the user types) when the theme is not applied. It used not to be present when the FB theme was not activated. Anyway, that's fixed with the `type: "search"` property.

Florent

**Comment by fflorent** [comment]
@janodvarko I have merged. It conflicted with this commit:
https://github.com/firebug/firebug.next/commit/65bc23f1cdf85ef841c0668fecfacfdb11352d70#diff-47fdb22747526f630f4a20d50d352a7fR165

I took my version of the patch as it works with Nightly. Feel free to adapt it as you would like.

Florent

**Comment by janodvarko** [comment]
@fflorent  looks good to me.

Honza
