### ISSUE TITLE
Network : The native filter box is moved to the left

### ISSUE THREAD

**Issue by fflorent** [firebug/firebug.next#439]
**STR:**
1. Open Firebug
2. Open the Network panel using the Firebug.next theme
3. Switch to the light theme
4. Go back to the Network panel

**Actual Result:**
The native filter box has been moved to the left
![Actual Result](https://cloud.githubusercontent.com/assets/371705/11103083/9b545efe-88c0-11e5-8edb-50356ae8195f.png)

**Expected Result:**
It should be at the bottom-right as it is without Firebug:
![Expected result](https://cloud.githubusercontent.com/assets/371705/11103053/7d13a9f4-88c0-11e5-814f-9c8dd64a8b3c.png)

**Comment by fflorent** [comment]
@janodvarko I propose a fix with the commit above + a question here:
https://github.com/firebug/firebug.next/commit/02b9dce9abf1a17c0618e68ba3fbbaedd43910a0#diff-14c22f0115d7dedea42a63de4f4cf7d9R149

Florent

**Comment by janodvarko** [comment]
> I propose a fix with the commit above + a question here:

Great, works for me.
And yes, using CSS is better.

Thanks!
Honza

**Comment by fflorent** [comment]
Merged. Thanks for the review Honza.

Florent
