### ISSUE TITLE
Search box regression : disapeared after 98654a3

### ISSUE THREAD

**Issue by fflorent** [firebug/firebug.next#441]
The searchbox isn't displayed anymore after this commit: 98654a3

ping @janodvarko 

Florent

**Comment by janodvarko** [comment]
@fflorent: can you paste a link?
I don't see this commit: ac9ce78ef072fafaa45a0f993ddc0c6d2

Honza

**Comment by fflorent** [comment]
Sorry, wrong commit. Here it is: 98654a3

**Comment by janodvarko** [comment]
This should be fixed after refactoring I did in the past two days.
(removing duplicated code and use all from FBSDK)

@fflorent please let me know if it doesn't work for you.

Honza
