### ISSUE TITLE
No toolbar button, nothing extra in devtools: it's only an entry in about:addons.

### ISSUE THREAD

**Issue by darkred** [firebug/firebug.next#443]
I just built a new Firefox xpi via:
_initially I had:_
```
git clone https://github.com/mozilla/jpm
npm install
npm link

git clone https://github.com/firebug/firebug.next 
npm install
```
so I just ran this:
```
git pull
npm install     (just in case)
jpm xpi
```
but after updating to the new xpi, the addon is not enabled:
there's no toolbar button, no toolbar button, nothing extra in devtools: it's only an entry in about:addons.

Here is the produced xpi (798 KB, the one from yesterday was 820KB)
https://www.dropbox.com/s/vmm19chwlcnxf4r/firebug%40software.joehewitt.com-3.0.0-beta.1.xpi?dl=0

installed versions:
node.js 5.0.0 x64
npm 3.3.6
jpm  1.0.3
using Firefox 45 Nightly x64 2015-11-16 in win 10 x64

**Comment by janodvarko** [comment]
Please do:
npm update

... to get the latest Firebug SDK 0.6.17
I just published it.

Does it help?

Honza

**Comment by darkred** [comment]
Yes, this solved it. Thank you.
