### ISSUE TITLE
Side panel tabs overflow without option to display them

### ISSUE THREAD

**Issue by SebastianZ** [firebug/firebug.next#445]
When the side panels are horizontally too small to display their tabs completely, they overlap on the outer border of Firebug, though there is no option to bring them into display.

![Side panel tabs overflow](https://cloud.githubusercontent.com/assets/958943/11234318/02b855b8-8dc7-11e5-8cba-3925a6e36d58.png)

When switching away from the Firebug theme and back to it and resize the side panels you'll see an overflow menu button:
![Side panel tabs with overflow menu arrow](https://cloud.githubusercontent.com/assets/958943/11234372/89332d7a-8dc7-11e5-8da3-d71570ef95bb.png)

Though that button disappears when you shrink the side panels again, i.e. it's not positioned correctly.
So one solutions to this is to correct the display of this side panel overflow button.
A second solution would be to have scroll arrows at the left and right of the panel tabs in this case like for the main panel tabs.

Sebastian

**Comment by janodvarko** [comment]
Thanks for the report, should be fixed now, let me know if not.

Honza

**Comment by SebastianZ** [comment]
Works. Thanks for the quick fix!

Sebastian
