### ISSUE TITLE
Side panels toggle button isn't displayed correctly within Inspector panel

### ISSUE THREAD

**Issue by SebastianZ** [firebug/firebug.next#446]
The side panels toggle button has a wrong display within the *Inspector* panel. It shows the DevTools icon instead of the Firebug one.

![Side panels toggle button in *Inspector* panel](https://cloud.githubusercontent.com/assets/958943/11234486/9a86ea20-8dc8-11e5-821e-54430282a50b.png)

Sebastian

**Comment by janodvarko** [comment]
Just fixed by https://github.com/firebug/firebug.next/commit/b363
493d5ffb6e92618fc4d56ecbcaa69d620703

Let me know if it doesn't work for you

Honza

**Comment by SebastianZ** [comment]
It's fixed now. Thanks!

Sebastian
