### ISSUE TITLE
Panel stays empty when Firebug is opened while a page is not fully loaded yet

### ISSUE THREAD

**Issue by SebastianZ** [firebug/firebug.next#448]
If a page is not completely loaded yet and you open Firebug, the *Inspector* panel stays empty.

![Empty *Inspector* panel](https://cloud.githubusercontent.com/assets/958943/11234773/84631842-8dcb-11e5-91ce-1ab84ebf1f3b.png)

There is an error shown within the Browser Console, which might be related:

> "Protocol error (unknownError): [Exception... "Unexpected error"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/highlighters/utils/markup.js :: CanvasFrameAnonymousContentHelper.prototype._insert :: line 236"  data: no]"1 Promise-backend.js:937

Sebastian

**Comment by janodvarko** [comment]
I can't reproduce it. Any specific page I should load?
Does it happen only if Firebug theme is active?


Honza

**Comment by SebastianZ** [comment]
It's obviously not a Firebug issue, it also happens when Firebug is not installed.
I filed it as [bug 1226154](https://bugzilla.mozilla.org/show_bug.cgi?id=1226154).

Sebastian
