### ISSUE TITLE
Check mark not updated when toggling split console

### ISSUE THREAD

**Issue by SebastianZ** [firebug/firebug.next#449]
When the split console is toggled via the *Tools* menu, the check mark is not set immediately but only after reopening the menu.

![Check mark not updated when toggling split console](https://cloud.githubusercontent.com/assets/958943/11234956/3e1f6294-8dcd-11e5-973f-5cb3fc294458.png)

One way to solve this could be by hiding the menu immediately once an option in it is chosen.

Sebastian

**Comment by janodvarko** [comment]
Should be fixed now, thanks for the report.

Honza
