### ISSUE TITLE
Search field shows two magnifier icons

### ISSUE THREAD

**Issue by SebastianZ** [firebug/firebug.next#453]
The search field shows two magnifier icons, one at the left and one at the right edge.
![Two magnifier icons shown in search field](https://cloud.githubusercontent.com/assets/958943/11235384/71ecfae2-8dd1-11e5-848b-25c7a4c5e64f.png)

Sebastian

**Comment by janodvarko** [comment]
Should be fixed now, thanks for the report

Honza
