### ISSUE TITLE
Show whether a CSS property, value or selector is valid

### ISSUE THREAD

**Issue by SebastianZ** [firebug/firebug.next#454]
Firebug 2 showed a green, red or yellow glowing arround the inline editor while editing CSS properties, values or selectors to indicate whether they are valid and can be applied.

This feature should be readded.

Sebastian

**Comment by fflorent** [comment]
Thanks Sebastian for the report.

I guess it should be reported as a Bugzilla issue (as it should be implemented on the native DevTools). Would you like to report it?

FYI, we currently triage Firebug issues so we only work on the theme.

Florent

**Comment by SebastianZ** [comment]
I filed it as [bug 1227054](https://bugzilla.mozilla.org/show_bug.cgi?id=1227054). In the hope that this gets implemented on the platform, I close this issue.

Sebastian
