### ISSUE TITLE
Work Fine in Firefox 42

### ISSUE THREAD

**Issue by mikhoul** [firebug/firebug.next#458]
Just to let you know that it seem to  work fine in Firefox 42.

I was using Firebug 3 beta 1  since the realese and to day I see the update but the RDF file was not allowing me to update .

So I've read the description and see the FF 44 "warning" (even the beta 1)  I just edited the RDF file and everything seem fine. :smiley:

**Comment by janodvarko** [comment]
What change did you put into the rdf file?

Is there anything I could fix here or it's only "good news everyone" kind of issue? ;-)

Honza

**Comment by mikhoul** [comment]
I just changed the version "minimum" from 44 to 42 to be able to install it on my Firefox 42 since the previous beta was working fine on Firefox 42.

Nothing really to change unless you want lower the minimum version from Firefox 44 to 42, maybe there is some "tools/functions" that I don't use that don't work on version lower than FF44 but I did not see them. :wink:

Best Regards ! :blush:

**Comment by janodvarko** [comment]
The reason why I changed the min version is that after uploading the *.xpi on AMO I want user to be updated slowly. First those who are using 44+ (currently DevEdition).

This might yet change to 45+ actually.

Honza
