### ISSUE TITLE
Please sign firebug.next

### ISSUE THREAD

**Issue by KuTi** [firebug/firebug.next#462]
Today, I update firefox to version 43.
This change log: http://www.ghacks.net/2015/12/15/firefox-43-find-out-what-is-new/
Please signed plugin for next version.

Thanks.

**Comment by qwertychouskie** [comment]
Until it is signed, set "xpinstall.signatures.required" in about:config to false to be able to use it.

**Comment by KuTi** [comment]
Thanks, I've config it to use a new version of Firebug, i hope  will signed it in the next version

**Comment by fflorent** [comment]
A beta version of Firebug will be submitted to addons.mozilla.org. This one will be signed.

Florent

**Comment by qwertychouskie** [comment]
> A beta version of Firebug will be submitted to addons.mozilla.org. This one will be signed.
Where? I can't find it.
