### ISSUE TITLE
Update releases at getfirebug.com

### ISSUE THREAD

**Issue by SebastianZ** [firebug/firebug.next#466]
The last two beta releases of Firebug 3 were not added to https://getfirebug.com/releases/firebug/3.0/ and the update.rdf also wasn't adjusted. This means that people won't get the current versions automatically.

Sebastian

**Comment by janodvarko** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1227926

Honza

**Comment by janodvarko** [comment]
Platform fixed
