### ISSUE TITLE
Not working in FF 47+

### ISSUE THREAD

**Issue by Komanc** [firebug/firebug.next#473]
Firebug is not working in FF 47+. It is disabled. According to http://mzl.la/1J7Lcsp (last paragraph) it must be signed. Is possible to sign it even if it is in "beta"? Is it still in development?

**Comment by janodvarko** [comment]
Firebug.next has been integrated into build-in Firefox developer tools (v48). You might want to see:
https://hacks.mozilla.org/2016/04/developer-edition-48-firebug-features-editable-storage-inspector-improvements-and-more/

So, please use Firefox developer tools.

Honza
