### ISSUE TITLE
Firebug is not compatible to latest version of firefox(55)

### ISSUE THREAD

**Issue by nitin1tester** [firebug/firebug.next#485]
Actual Result
The latest version of Firebug is not supporting to the latest version of Firefox(55).
Expected Result 
The latest version of Firebug should be compatible with the latest version of Firefox.

**Comment by SeanDKendle** [comment]
Firebug is now deprecated.  It was rolled into the native Firefox Developer Tools and now ships with Firefox!  Just delete the plugin and use the built-in Developer Tools!

![image](https://user-images.githubusercontent.com/5393604/30113968-5dfd9aa4-92e4-11e7-8ad2-bc43b82c3ff3.png)

Firefox's DevTools were developed by the Firebug add-on author.

You can switch DevTools to a Firebug skin:

https://blog.getfirebug.com/2016/02/08/merging-firebug-into-the-built-in-firefox-developer-tools/

**Comment by snpanigrahi9** [comment]
Any ETA  for firebug 3 to be released ?

**Comment by janodvarko** [comment]
Firebug.next has been integrated into DevTools and this repo is deprecated.
https://blog.getfirebug.com/2016/02/08/merging-firebug-into-the-built-in-firefox-developer-tools/
Honza
