### ISSUE TITLE
Conflict with Firebug 2

### ISSUE THREAD

**Issue by simonlindholm** [firebug/firebug.next#95]
If I enable both Firebug and Firebug.next in the same profile:
- Firebug 2's command line stops working.
- If I restart, Firebug 2 fails to open.

Not sure why this happens, but it would be really nice to be able to use both at the same time (for trying out FB.next without having to uninstall FB2, falling back to Firebug 2 when something is missing, etc.)

**Comment by janodvarko** [comment]
We are not planning to run Firebug 2 and Firebug 3 side by side, so closing this bug.

Honza
